export { default as DisinfestazioneView } from './DisinfestazioneView';
export { default as SanificazioneView } from './SanificazioneView';
export { default as TemperatureNegativeView } from './TemperatureNegativeView';
export { default as TemperaturePositiveView } from './TemperaturePositiveView';
export { default as AnomalieView } from './AnomalieView';
export { default as ManualeHACCPView } from './ManualeHACCPView';
export { default as ProdottiVenditaView } from './ProdottiVenditaView';
export { default as ColazioneAcquavivaView } from './ColazioneAcquavivaView';
export { default as SchedeTecnicheView } from './SchedeTecnicheView';
