"""
magazzino_bar_seed.py
---------------------
Prodotti di default del magazzino bar, usati SOLO al primo avvio per popolare
la collezione magazzino_bar_prodotti se vuota (vedi seed_magazzino_bar()).
Estratto da magazzino_bar.py per snellire il router.
"""

PRODOTTI_DEFAULT = [
    # ──────────────────────────────────────────────────
    # PASTICCERIA
    # ──────────────────────────────────────────────────
    {
        "nome": "AMARENA INTERA TANTOFRUTTO CAL16/18 IN SCIROPPO KG2,75(02004275)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "AMARENA NATURALE INTERA IN SCIROPPO DA KG 3",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "AMARENA VISCIOLA 15Kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "amarene",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "amido",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "AMIDO ARTECREMA CONFEZIONE DA 1 KG",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "AMIDO ARTECREMA CONFEZIONE DA 20 KG",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "AMIDO DI RISO IN POLVERE 90 MICRON DA KG 1",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "AMIDO IN POLVERE DA 1Kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "AROMA ALCOLICO CUBANO SCURO 70^ LT 2",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "AROMA BRIOCHES",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "AROMA CROISSANT",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "AROMA EMULSIONE PANETTONE NATURALE",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "AROMA IN PASTA LIMONE 1kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "AROMA PASTA FRAGOLA",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "AROMA PISTO SUPER EXTRA IN POLVERE",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "AROMA VANIGLIATO 94^ LT 2",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "BAGNA BENEVENTO 70%VOL 2lt",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "BARCHETTA FROLLA MIGNON LUNGHEZZA mm 67 PZ 250",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "BASE PASTA DI MANDORLE MO ORO CONFEZIONE DA KG 12,5",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "BIFFI GR.100 SALSA DI FICHI",
        "categoria": "Pasticceria",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "CACAO DA 1 KG ROSSO BRUNO 22/24 CORPO PIENO VAN HOUTEN",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CANNOLI MAX SCURI x 100pz",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "CHUNKS CUBETTI AL PISTACCHIO DA KG 2",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CIAMBELLA MAXI ZUCCHERATA G. 100",
        "categoria": "Pasticceria",
        "fornitore": "Dolciaria Acquaviva S.P.A. Sog. All'Att. Di Dir. E",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "CIAMBELLA MINI ZUCCHERATA g. 22/25",
        "categoria": "Pasticceria",
        "fornitore": "Dolciaria Acquaviva S.P.A. Sog. All'Att. Di Dir. E",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "CILIEGIE CALIBRO 18/20 ROSSE CANDITE DA KG 2,5",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "coda d'aragosta",
        "categoria": "Pasticceria",
        "fornitore": "Dolciaria Acquaviva S.P.A. Sog. All'Att. Di Dir. E",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "CODA D'ARAGOSTA MIG.GR.28/30",
        "categoria": "Pasticceria",
        "fornitore": "Dolciaria Acquaviva S.P.A. Sog. All'Att. Di Dir. E",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "COLORE IDROSOLUBILE ROSSO GR 150 (IDRO150RSS)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "COVER PISTACCHIO ROCK DA KG 3 (011CP130)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CREMA NOCCIOLA (13%)SOFT DA FARCITURA KG 6 (42000344/NP075 SOFT)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CREMA PAN DI STELLE SPALMABILE IN CONFEZIONE DA KG 3",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CREMA RIO GRAN TRADIZIONE NOCCIOLA DA KG 13",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CREMA RIO TRADIZIONE PISTACCHIO IN CONFEZIONE DA KG 5 (DC00BM)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CUBETTI MISTI 3X3 5kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CUBETTI MISTI 5kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "DIAVOLINI COLORATI IN CONFEZIONE DA GR 500",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "ESSENZA BRIOCHE ML 500",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "ESSENZA CANNELLA GR 500",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "ESSENZA NEROLY BIGARADE GR 80",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "EST.ZUPPA INGLESE",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "F.NUTELLA K.3",
        "categoria": "Pasticceria",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "FIORUCCI MORTADELLA AROMA C.P.",
        "categoria": "Pasticceria",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "FORM STAC 400ml",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GELATINA A FREDDO",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GELATINA GELINA A FREDDO NEUTRA IN CONFEZIONE DA KG 6",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "gelatina neutra",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GOCCE DI MERINGA SFUSO KG 2",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "GOCCINE MIGNON DI SURROGATO FONDENTE 1000/HG DA KG 12",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "GRANELLA DI NOCCIOLE TOSTATE",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GRANELLA DI PISTACCHI",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GRANELLA PISTACCHIO CALIBRO 2/4 DA KG 1",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "HALTA STRUTTO GR.250",
        "categoria": "Pasticceria",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "L.3172514A",
        "categoria": "Pasticceria",
        "fornitore": "Granzuccheri Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "LIEVITAL LIEVITO GR.25 X20",
        "categoria": "Pasticceria",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "LIEVITO BACK PULVER CHIMICO DA KG 2,5 + BRICCO GRADUATO",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "LIEVITO DA KG 5 NATURALE NATURVI-S (4849)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "LIEVITO x 2.5kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MAGIC FONDANT DA KG 14",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MANDORLE NATURALI IN CARTONI DA KG 10",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "margarina crema",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "margarina sfoglia",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "MELA CANNELLA A CUBETTI 14X14 SEMICANDITA IN SCIROPPO DA KG 3",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MELANGE PLUS HOMILLINA GATEAUX DA KG 10 (4156)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MEZZELUNE DI GELATINA AL LIMONE KG 2",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MIGLIORATORE XXL FORZA IN CONFEZIONE DA KG 8",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MIX AFRICANO MIX DA KG 10",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "mix cake nature da kg 10 (4830)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MIX GLAXA (4495)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "MIX GOLDEN NOW DA KG 15 (4644)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MIX YOGOFINE DA KG 15",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "nuppy nocciola 12kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "nuppy pistacchio piu' 6kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "NUTELLA KG.3",
        "categoria": "Pasticceria",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "OLVA THERMO CREMA GATEAUX",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "OLVA THERMO QUICK",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PASTA DI MANDORLA MANDOLPAN 15kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "pasta di mandorle",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PASTA NOCCIOLA 5,5kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PASTA PISTACCHIO PURO 2,5KG",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PERE A CUBETTI 10X10 SEMICANDITE IN SCIROPPO KG 3",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "QUADRATI BIANCHI STRIATI ROSSI/NERI 3 CM DA 220 PZ (1034182)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "SCAGLIETTA DI SURROGATO FONDENTE RIO DA KG 2 (DS00AG)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SCAGLIETTA FONDENTE x 1kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SCORZA PALERMO MEDIA PZ 100 (145 MM)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "SCORZA PALERMO MIGNON DA KG 3,5 (85MM)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SCORZONE A FILETTI ARANCIO 6X80 CANDITI DA KG 2",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SCORZONE ARANCIO FRESCO PREMIUM CUBETTI 10X10 CANDITO DA KG 3",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "semola",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "SEMOLA D'AUTORE PER RIPIENO DI SFOGLIATELLA IN CONFEZIO DA KG 5",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SEMOLA DI GRANO DURO x 5kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SFOGL.NAP.MIGNON GR.30",
        "categoria": "Pasticceria",
        "fornitore": "Dolciaria Acquaviva S.P.A. Sog. All'Att. Di Dir. E",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": 'SIGILLO ROSSO "MERRY CHRISTMAS" DIAM.3CM 175PZ 14616',
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "SOTTOGELI GRANDI PZ 2000 CM 13",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "STRUTTO",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "STRUTTO PAPILLON EXTRA IN SECCHIO DA KG 15",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "STRUTTO RAFFINATO I B VERDE",
        "categoria": "Pasticceria",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "STRUTTO RAFFINATO UN�GR� KG.25",
        "categoria": "Pasticceria",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SURROGATO BIANCO SUPERBRILL IN CONFEZIONE DA KG 10",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SURROGATO FONDENTE SUPERBRILL250 IN CONFEZIONE DA KG 10",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "TAPPI MIGNON PER SFOGLIATE GR.20",
        "categoria": "Pasticceria",
        "fornitore": "Dolciaria Acquaviva S.P.A. Sog. All'Att. Di Dir. E",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "TAPPI PER RICCE GRANDI DA GR 55/60 SURGELATO",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "TAPPI PER RICCE MIGNON DA GR 18 SURGELATO",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "TAPPI  GRANDI  G 55/60",
        "categoria": "Pasticceria",
        "fornitore": "Dolciaria Acquaviva S.P.A. Sog. All'Att. Di Dir. E",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "tartalletta",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "TARTALLETTE MIGNON x 250Pz",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "TARTELLETTE GRANDI",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "topping caramell",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "TOPPING CARAMELLO DA KG 1 (PC315)",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "turbo da kg 5",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "UVA DA KG 1 SULTANINA AUSTRALIANA VINTAGE",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "uva sultanina",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "UVA SULTANINA AUSTRALIANA VINTAGE CONFEZIONE DA KG 14",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "visciola",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "VISCIOLA PER PASTICCERIA 5Kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "zucchero a velo",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO A VELO 5 KG.",
        "categoria": "Pasticceria",
        "fornitore": "Granzuccheri Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO A VELO IMPALPABILE DA 5 KG",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO A VELO x 5kg",
        "categoria": "Pasticceria",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO FONDENTE PURA CANNA 15 KG",
        "categoria": "Pasticceria",
        "fornitore": "Granzuccheri Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO IN GRANELLA 10 KG.",
        "categoria": "Pasticceria",
        "fornitore": "Granzuccheri Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO IN GRANELLA GRANDE",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO IN GRANELLA MEDIA",
        "categoria": "Pasticceria",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    # ──────────────────────────────────────────────────
    # ROSTICCERIA — ALIMENTARI
    # ──────────────────────────────────────────────────
    {
        "nome": "AMBROSOLI MIELE M.FIORI GR.250 VAS",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "AURICCHIO FETTA PICCANTE GR.200",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "AURICCHIO GIOVANE SALAMINI KG.",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "BARILLA PAS.BRO.GR.500 FUSILLI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "BARILLA PAS.BRO.GR.500 PENNE RIGAT",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "BARILLA PESTO GR.190 GENOVESE S.AG",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "BARILLA RIP.GR.250 TORTELLINI PROS",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "BELLA LODI FORM.ITAL.FORME 18 MESI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "BERNI FUNGHI CHAMPIGNON NAT.GR.400",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "BIFFI BUSTINE OLIO EVO ML10 PZ.100",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "BIFFI BUSTINE SALE PZ.500",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "BIRAGHINI   G.400 BIRAGHI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "BONDUELLE GR.330 VETRO CANNELLINI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "BONOMELLI CAMOMILLA SETACCIATA 18F",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "BONTA'DIVINA TIRAMISU' 1' GR.450",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "BRUNELLI PECOR.STAG.RIS.TRAIANO KG",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "BUONDÌ GR.198 CLASSICO X6",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "CHEF BESCIAMELLA ML.200",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "CIOLI PORCHETTA ARICCIA IGP 1/2 KG",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "COATI SPIANATA PICCANTE 1/2 SV",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "COMARO MIELE M.FIORI GR250 SQUEEZE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "CURTIRISO KG.1 CARNAROLI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "DAILYBREAD PAN DI SEGALE GR.500",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DAILYBREAD PANE 4 CEREALI GR.500",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DAMICO GR.300 GIARDINIERA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DAMICO LATTA GR.400 PEPERONI ARROS",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DANTE LT.1 OLIO CONDISANO",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "DE CECCO PAS.GR.500 117MEZ.ZITA TA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DE CECCO PAS.GR.500 120PASTA MISTA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DE CECCO PAS.GR.500 170VERMICELLI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DE CECCO PAS.GR.500 24RIGATONI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DE CECCO PAS.GR.500 2MAFALDINE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DE CECCO PENNE LISCE 140",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "DE CECCO TUBETTI LISCI 62",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "DE CECCO.OLIO LT.1 EVO CLASSICO",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "DECECCO MEZZA ZITA 117",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "DECECCO SPAGHETTONI 412",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "DESANTIS OLIO EXTRAV.ITALIANO LT.1",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "DESANTIS PET LT.1 OLIO ARACHIDE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "DESANTIS PET LT.1 OLIO GIRASOLE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "DESANTIS PET LT.1 OLIO MAIS",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "DIVELLA GR.500 SPEC.2ZITI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DIVELLA GR.500 SPEC.3MEZZANI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DIVELLA PASTA GR.500 41MISTA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DIVELLA PASTA GR.500 62PATERNOSTI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DIVELLA PASTA GR.500 9SPAGHETTINI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "DIVELLA REGIONALI GR500 19PANTACCE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "DIVELLA REGIONALI GR500 85FARFALLE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "DIVELLA REGIONALI GR500 88FIOCCHET",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "ERIDANIA KG.1 ZUCCH.CLASSICO ASTUC",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "FAGIOLI BORLOTTI da KG.3X6",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "FAGIOLI CANNELL LESSATI KG.3X6",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "FARINA 0/MAN. CAPUTO DA KG.25",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "FARINA 00 CAPUTO RINFORZ.KG.25",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "FUNGHI CHAMP CASARECCIA KG.3X6",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "GEPI PORCHETTA ARROSTO AROM.STV KG",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "GRANCUCINA BESCIAMELLA ML.500",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GRATT.GRANB.G.100 BIRAGHI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "GRATT.PECOR.G.100 BIRAGHI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "HEINZ GR.855 MAIONESE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "HEINZ KG.1 KETCHUP",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "HERO POKER CONFET.GR.100 CILIEGIA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "HERO POKER CONFET.GR.100 FRAGOLA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "HERO POKER CONFET.GR.100 FRUT.BOSC",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "HERO POKER MIELE DI FIORI GR.100",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "ICEBERG     G.200 SENDERO",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "IMETTE   GR.200       YMA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "INSALATE VASCHET. SENDERO",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "ITALKALI SALE IODIO GROSSO KG.1",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ITALPEPE V.ERBA CIPOLLINA GR.4",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "KINGS P/CRUDO SAN DANIELE S/O",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "KNORR GRANPURE'GR.225",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "KOSÈ CIALDE DECISO PZ.50",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "KRAFT.MAIONESE TUBO ML.150",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "MAIS BONDUELLE GR.300X12",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "MARG WIENER PLUNDERPLAT KG.2X5",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MARGAR WIENERCREME DA KG.2,5X4",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MAYONESE GAJA da KG.5",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MIGLIORATORE UNIVERSALE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "MILKA.TAV.GR.90 EXTRA COCOA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "MIX ALLEGRO G.200 SENDERO",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "MOND.PHILADELPHIA GR.25X6 PORZ.",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "MOND.SOTTILETTE GR.400",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "MORATO AMERICAN SANDWICH GR.550",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "NORITA SALMONE NORV.GR.100 BUSTA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "OLIO SEMI GIRASOLE DA L.25",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "OLIO SEMI GIRASOLE SORRENTO L.25",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "OLIOVE NERE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Olive Miraglia S.R.L. 1890",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "OLITALIA LT.1 OLIO GIRASOLE PET",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "P.CRUDO S/O MEC   SENDERO",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "P.CRUDO S/O        ASSISI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Panuozzo 350 g",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Società Duegi S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PAR.REGG.   G.900 SORESIN",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "PARMAREGGIO GRATT.GR.60 PAR/REG.",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "PARODI FIL.ALICI CANTABRIC.GR90 V.",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PASSATA ALBICOCCA LABO GARDEN FRUIT DA KG 12,5",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PASSATA ALBICOCCA x 10kg",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PASSATA VISCIOLA LABO GARDEN FRUIT DA KG 12,5",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PASTA DE CECCO BUCATINI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PASTA DE CECCO Mafaldine",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PASTA DE CECCO P.LISCE 140",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PASTA DE CECCO RIGATONI",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "pasta fragola",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PASTA REALE CONFEZIONE DA KG 12,5",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PASTA TIRAMISU' DA KG 1 (0227.1)",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PEPE NERO MACINATO BUSTA KG.1",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PEZZELLA MILLEFIORI GR.60 X35",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "PINNA BRIGANTE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PINNA BRIGANTE DI CAPRA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PINNA PEC.ROMANO DOP TORO BI.1/4 S",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PINSAMI PINSA CLASSICA GR.230",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "PISELLI BONDUELLE GR.580X12",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "POMÌ PASSATA BRICK GR.750",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "PORCH.MONTAGNA1/2 SENFTER",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PREP.VEGETA.M.1000 HOPLA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "prep.vegeta.ml.500 hopla",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "RIGAMONTI BRES.VALTEL.ORO.IGP 1/2",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "RIO MARE TONNO O.OLIVA GR.65 X6",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "ROBERTO GRAN PIADA GR.330 INTEGRAL",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "SALE FINO ITALKALI DA KG.1X12",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SALE GROSSO ITALKALI KG.1X12",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SARDANELLI MAREVIVO O.S. GR.80X3",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "SEMOLA 0 G MEDIA XXL MAD KG.25",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SEMOLA 0 G.MEDIA MAD da KG.12.5",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SOGNI D'ORO CAMOMILLA MELATONI.GR6",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "sottilette",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "soya classic lt.1 valsoia",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "STAR TEA 25FF CLASSICO",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "TONNO CALLIPO OL.OLIVA G.80x48",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "TONNO CALLIPO OL.OLIVA G.80x96",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "VIGNOLA KG.1 RISO RIBE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "VIT BOBINA X2 CASA&LAVORO 800 PROF",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "VITTORIA GR.250 LUPINI AL SALE",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "WELCOME FETTE GR.200",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "WELCOME FETTE GR.800",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "wrustel",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "WUDY CLAS.4XG.125 AIA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "WUDY CLASS. G.300 AIA",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "YMA.KG.5 OLIVE GRECIA V.SSM",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO IN BUSTINE BAR 10 KG.",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Granzuccheri Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO IN BUSTINE BAR DI CANNA 5 KG.",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "Granzuccheri Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO RAF.SEM. ERIDANIA KG.25",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO RAF.SEM.ERIDANIA KG.25",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "zucchero semolato",
        "categoria": "Rosticceria — Alimentari",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    # ──────────────────────────────────────────────────
    # BAR — BIBITE
    # ──────────────────────────────────────────────────
    {
        "nome": "AVENA  DRINK LT.1 VALSOIA",
        "categoria": "Bar — Bibite",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "Cannoli medi cioccolattati pz 100",
        "categoria": "Bar — Bibite",
        "fornitore": "Ge.Fi.Al. Sas Di Fiorenzano Gennaro & C.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "Cannoli medi cioccolattati pz 100 // lotto 11 Settembre scadenza Marzo 2026",
        "categoria": "Bar — Bibite",
        "fornitore": "Ge.Fi.Al. Sas Di Fiorenzano Gennaro & C.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "Cannoli mignon cioccolattati kg 3,5",
        "categoria": "Bar — Bibite",
        "fornitore": "Ge.Fi.Al. Sas Di Fiorenzano Gennaro & C.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "Cannoli mignon cioccolattati kg 3,5 // lotto 11 settembre scadenza 2026",
        "categoria": "Bar — Bibite",
        "fornitore": "Ge.Fi.Al. Sas Di Fiorenzano Gennaro & C.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CHUNKS - CUBETTI DI CIOCCOLATO AL LATTE DA KG 2,5",
        "categoria": "Bar — Bibite",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CHUNKS - CUBETTI DI CIOCCOLATO BIANCO DA KG 2,5",
        "categoria": "Bar — Bibite",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "CHUNKS - CUBETTI DI CIOCCOLATO FONDENTE DA KG 2,5",
        "categoria": "Bar — Bibite",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "cioccolato",
        "categoria": "Bar — Bibite",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "DENOCCIOLATE NERE KALAMON IN ACQUA E SALE PROVENIENZA GRECIA POLIGROS",
        "categoria": "Bar — Bibite",
        "fornitore": "Olive Miraglia S.R.L. 1890",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GRANAROLO BEVANDA LT.1 DI SOIA UHT",
        "categoria": "Bar — Bibite",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "GRANAROLO BEVANDA LT.1 RISO UHT",
        "categoria": "Bar — Bibite",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "OLIVE VERDI TONDE 0000 MSM IN ACQUA E SALE PROVENIENZA ITALIA,SICILIA,CAMPOBELLO DI MAZARA (TP)",
        "categoria": "Bar — Bibite",
        "fornitore": "Olive Miraglia S.R.L. 1890",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "SURROGATO CIOCCOLATO FONDENTE",
        "categoria": "Bar — Bibite",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "cf",
        "stock": 0,
    },
    # ──────────────────────────────────────────────────
    # ROSTICCERIA — SALUMI
    # ──────────────────────────────────────────────────
    {
        "nome": "AIA. WUDY GR.300 WURSTEL POLLO",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "ARTIGIAN PANCETTA COPPATA 1/2 STV",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "BERETTA P/COTTO ALLA BRACE",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "BOMBIERI SALAME NAPOLI",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "BONAZZA WURSTEL KG.1 GRIGLIA&FAMIG",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "COATI SALAME NAPOLI SV",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "FINI P/COTTO LUSSO ADDOBBO",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "FIORUCCI P/COTTO VELLUTATO",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GOLOSITA'SALUMI/FORMAGGI STV KG.1",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "GRANO COTTO x 2.5kg",
        "categoria": "Rosticceria — Salumi",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "IL COLLE LARDO PANCETTATO STV KG.",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "LEONCINI CUBETTI P/COTTO GR.100",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "MORGANTE WURSTEL GR.100 MORGHÌ",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "p.cotto s/p.rosso sendero",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "p.cotto verde    rosafino",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "salame",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "SALAME NAPOLI SV. SENDERO",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "SALAME SUINO      SENDERO",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "SENFTER SPECK MONTAGNA 1/2 STV KG.",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "TULIP.BACON/PANCETTA AFFUM.KG.1",
        "categoria": "Rosticceria — Salumi",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    # ──────────────────────────────────────────────────
    # LATTICINI E FORMAGGI
    # ──────────────────────────────────────────────────
    {
        "nome": "AROMA EMULSIONE BURRO NATURALE",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "BURRO TRADIZIONALE BLOCCHI M.G. 82% 20665601",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "burro  g.  8 porzioni yma",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "CHEF PANNA DA CUCINA ML.200",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "CHEF PANNA FUNGHI ML.125X2",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "CHEF PANNA SALMONE ML.125X2",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "ESSENZA BURRO ML 500",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "FIOR DI LATTE",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Gargiulo Giuseppe",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "FIORI E PROVOLA",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Cilatte S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "granapadano",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GRANAPADANO G.900 SORESIN",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "GRANAPADANO KG.1  SORESIN",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "GRANAROLO LATTE P.S. LT.1 BRIK",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "GRANCUCINA PANNA ML.200",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GRANCUCINA PANNA ML.500",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "GRIFO L'ABATE CACIOTTA NORCIA KG.3",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "latte",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "LATTE AP.INT.4/4 DIPIU",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "LATTE AP.P.S.4/4 S/LATTOS",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "LATTE AQ.INT.4/4 YMA BAR",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "LATTE FR.P.S.4/4 PET AMOD",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "LATTE   1000 INT.UHT  YMA",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "LATTE   1000 SCR.UHT  YMA",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "LATTMANTOVA GRANA PADANO 1/8 STV",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "LURPAK BURRO GR.200 CLASSICO S/SAL",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "MASCARPONE G.250      YMA",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "MELANGE PLUS HOMILLINA PLATTE DA KG 10 (4155)",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MILKNUT (LATTE E NOCCIOLA) DA KG 6",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "OPTIMUS MASCARPONE GR.250",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "panna",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PANNA ML.200 CUCINA   YMA",
        "categoria": "Latticini e Formaggi",
        "fornitore": "G.I.A.L. Generale Ingrosso Alimentare S.R.L.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "PANNA SPRAY ZUCCHERATA ML 700",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "PANNA TENUTAPIU' DA LT 1 (M.G. 38%)",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "PANNA VEG GRAN CUCINA ML.500X20",
        "categoria": "Latticini e Formaggi",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "PARMAREGGIO BURRO GR.100",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "PARMAREGGIO BURRO GR.200",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "PASTA GLASSATURA LATTE PATE A GLACER DA KG 5 (Blonde)",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PINNA PECORINO TORO BIANCO 1/8 SV",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Ricotta di Pecora Zuccherata Congelata x 6 - Ricocrem-",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Ge.Fi.Al. Sas Di Fiorenzano Gennaro & C.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "RICOTTA FULVI INCART.",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Gargiulo Giuseppe",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "RICOTTA FULVI INCARTATA",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Gargiulo Giuseppe",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "RICOTTA OMOGENEIZZATA II 5KG",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Gargiulo Giuseppe",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "RICOTTA TIPO ROMA",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Gargiulo Giuseppe",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Ricotta Zuccherata Congelata",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Gargiulo Giuseppe",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "RICOTTA ZUCCHERATA CONGELATA CAV.",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Gargiulo Giuseppe",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "SORESINA BURRO MONODOSE GR.125",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "SORESINA GR.100 GRATT.GRANAPADANO",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "SORESINA GRATT.GR.100 GRANAPADANO",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "STERILGARDA LATTE LT.1,5 P.S. BRIK",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Big Food Srl",
        "unita": "l",
        "stock": 0,
    },
    {
        "nome": "TARTELLETTA (063213) MODERN DOLCE C/BURRO 43MM PZ 250 (SFUSO)",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "TARTELLETTA (063915) MODERN DOLCE CON BURRO 65MM PZ 90(BLISTER)",
        "categoria": "Latticini e Formaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "pz",
        "stock": 0,
    },
    # ──────────────────────────────────────────────────
    # BAR — VINI E LIQUORI
    # ──────────────────────────────────────────────────
    {
        "nome": "CACAO AMARO IN POLVERE x 1kg",
        "categoria": "Bar — Vini e Liquori",
        "fornitore": '"Rondinella Market S.R.L."',
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "Cassatina Monoporzione Classica Gr. 100 x 12 pz.",
        "categoria": "Bar — Vini e Liquori",
        "fornitore": "Ge.Fi.Al. Sas Di Fiorenzano Gennaro & C.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "LIEVITO DI BIRRA PER PANIFICAZIONE",
        "categoria": "Bar — Vini e Liquori",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "MOLINARI SAMBUCA EXTRA CL.70",
        "categoria": "Bar — Vini e Liquori",
        "fornitore": "Big Food Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "olio extravergine oliva",
        "categoria": "Bar — Vini e Liquori",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "OLIO EXTRAVERGINE OLIVA L.5",
        "categoria": "Bar — Vini e Liquori",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "RUMMO PAS.CLAS.GR.500 23ANELLI SIC",
        "categoria": "Bar — Vini e Liquori",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "RUMMO PAS.SPEC.GR.500 111PACCHERI",
        "categoria": "Bar — Vini e Liquori",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "UVETTA CILENA AL RUM SPIRITUALS IN SCIROPPO KG 2,75 (02024275A)",
        "categoria": "Bar — Vini e Liquori",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    # ──────────────────────────────────────────────────
    # UOVA
    # ──────────────────────────────────────────────────
    {
        "nome": "BARILLA PAST.UOVO GR.275 FARFALLIN",
        "categoria": "Uova",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": 'CATEGORIA "A" PIU\' TUORLO(PASTA GIALLA)PASTORIZZATO DA ALL.TERRA',
        "categoria": "Uova",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "EUROVO ALBUME STANDARD PASTORIZZATO (NORMALE) (5197)",
        "categoria": "Uova",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "EUROVO TUORLO STANDARD PASTORIZZATO (NORMALE) (0066)",
        "categoria": "Uova",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "NUOVA BIANCALIEVE CREMA DA MONTARE",
        "categoria": "Uova",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {"nome": "tuorlo", "categoria": "Uova", "fornitore": "Saima S.P.A.", "unita": "cf", "stock": 0},
    {
        "nome": "tuorlo d'uovo pastorizzato",
        "categoria": "Uova",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "TUORLO D'UOVO PASTORIZZATO DA ALLEVAMENTO A TERRA",
        "categoria": "Uova",
        "fornitore": "Saima S.P.A.",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "uova",
        "categoria": "Uova",
        "fornitore": "Naturissime Srl",
        "unita": "cf",
        "stock": 0,
    },
    # ──────────────────────────────────────────────────
    # BAR — SNACK
    # ──────────────────────────────────────────────────
    {
        "nome": "PARMAREGGIO SNACK BOX KG.1 MITO",
        "categoria": "Bar — Snack",
        "fornitore": "Big Food Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PARMAREGGIO SNACK GR.100",
        "categoria": "Bar — Snack",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    # ──────────────────────────────────────────────────
    # ORTOFRUTTA
    # ──────────────────────────────────────────────────
    {
        "nome": "Ananas L. 055-000857-0003014",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "ARANCIA A TONDELLI CANDITA DA KG 5",
        "categoria": "Ortofrutta",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "Basilico orig.ita L.4206",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "BERNI MELANZANE FILETTI GR.290",
        "categoria": "Ortofrutta",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "CUBETTI SCORZA ARANCIA 3X3 KG 5",
        "categoria": "Ortofrutta",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "DEL MONTE ANANAS NAT XL GR.820",
        "categoria": "Ortofrutta",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "Friarielli Orig.Campania L.51/F FVI/49",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "Frutta Mista",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Iceberg L. 258-000743-0010367",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "Kiwi L. 060-000015-0000091",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Limes L.35219030060240253",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Melanzane L.197-002155-0008629",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Mele Stark Orig.Ita L.027-003659-0000799",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "Melone Giall orig. ita  L.05/42",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "PASSATA POMODORI POMOLA' KG.3",
        "categoria": "Ortofrutta",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "PASSATA POMODORO G.700 TORRENTE",
        "categoria": "Ortofrutta",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "PASTA DI ARANCIA (PUREA) AMORDIFRUTTA KG 3,5 (05100130A)",
        "categoria": "Ortofrutta",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "Patata da Consumo L.469/93",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Peperoni  L.031-004226-0000007",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Pere Conferenze L. 059-004082-0001270",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Pomodori Insalata Orig.Ita L89/F455",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "POMODORI PELATI KG.3 TORRENTE",
        "categoria": "Ortofrutta",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "POMODORINI CASARECCIA KG.3X6",
        "categoria": "Ortofrutta",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "Pomodorini Sicilia L. 291-002759-0000021",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Rosmarino L4204 289",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Scarola Liscia L.349/1483",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "Sedano L.F.183/A",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    {
        "nome": "VALLEPIÙ PESTO FRESCO S/AGLIO GR.9",
        "categoria": "Ortofrutta",
        "fornitore": "Big Food Srl",
        "unita": "g",
        "stock": 0,
    },
    {
        "nome": "Zucchine L.0950-04/21-000040IT",
        "categoria": "Ortofrutta",
        "fornitore": "I Cozzolino Srl",
        "unita": "cf",
        "stock": 0,
    },
    # ──────────────────────────────────────────────────
    # CARTA E IMBALLAGGI
    # ──────────────────────────────────────────────────
    {
        "nome": "CARTA DA FORNO SILICONATA CM 60X40 PZ 500",
        "categoria": "Carta e Imballaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "pz",
        "stock": 0,
    },
    {
        "nome": "MANDORLE NATURALI IN SACCHI DA KG 25",
        "categoria": "Carta e Imballaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "MIELE MILLEFIORI CONTENITORE KG 10",
        "categoria": "Carta e Imballaggi",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "SALE SACCHI SALTECHNO KG.25",
        "categoria": "Carta e Imballaggi",
        "fornitore": "F.Lli Fiorentino Srl",
        "unita": "kg",
        "stock": 0,
    },
    {
        "nome": "ZUCCHERO IN SACCHI 25 KG. SERA' FINO",
        "categoria": "Carta e Imballaggi",
        "fornitore": "Granzuccheri Srl",
        "unita": "kg",
        "stock": 0,
    },
    # ──────────────────────────────────────────────────
    # PULIZIA
    # ──────────────────────────────────────────────────
    {
        "nome": "AMMONIACA (BICARBONATO DI AMMONIO) E503 KG1",
        "categoria": "Pulizia",
        "fornitore": "Saima S.P.A.",
        "unita": "kg",
        "stock": 0,
    },
]
