"""Contratti operativi specifici delle 65 pagine canoniche di GestionaleCloud.

Questi contenuti descrivono il comportamento target della ricostruzione pulita.
Non sono una fotografia delle sole chiamate frontend: definiscono fonti, effetti,
automazioni, collegamenti, limiti e prove minime di correttezza pagina per pagina.
"""
from __future__ import annotations

from typing import Any


def page(
    sources: list[str],
    writes: list[str],
    flow: list[str],
    automations: list[str],
    links: list[str],
    guards: list[str],
    acceptance: list[str],
) -> dict[str, Any]:
    return {
        "sources": sources,
        "writes": writes,
        "flow": flow,
        "automations": automations,
        "links": links,
        "guards": guards,
        "acceptance": acceptance,
    }


PAGE_LOGIC: dict[int, dict[str, Any]] = {
    1: page(
        ["Identity provider", "utenti e ruoli", "configurazione MFA"],
        ["sessione autenticata", "audit accessi e tentativi falliti"],
        [
            "Validare credenziali lato server e applicare rate limit senza rivelare se l'utente esiste.",
            "Se MFA è richiesta, creare una sessione provvisoria e completarla solo dopo il secondo fattore.",
            "Caricare ruolo e destinazione richiesta, quindi reindirizzare esclusivamente verso una route autorizzata.",
        ],
        ["Scadenza sessione, blocco progressivo e revoca vengono applicati dal backend."],
        ["Ogni login riuscito o fallito è collegato all'audit dell'utente e alla sessione generata."],
        ["Cookie sicuri; nessun token nel localStorage; autorizzazione verificata nuovamente da ogni API."],
        ["Utente valido entra nella destinazione consentita; utente/MFA non validi restano fuori senza perdita del redirect sicuro."],
    ),
    2: page(
        ["sessione autenticata", "permessi area riservata", "registro operazioni riservate"],
        ["operazioni riservate tramite servizio dedicato", "audit prima/dopo"],
        [
            "Eseguire uno step-up di autenticazione prima di mostrare dati o comandi sensibili.",
            "Mostrare solo le funzioni concesse dal ruolo e spiegare perché una funzione non è disponibile.",
            "Per ogni mutazione mostrare anteprima, conseguenze, conferma forte ed esito verificabile.",
        ],
        ["Timeout breve e nuova autenticazione dopo inattività o cambio di contesto sensibile."],
        ["Ogni azione rimanda al record modificato e alla relativa voce di audit."],
        ["Nessun pagamento, cancellazione definitiva o elevazione di ruolo può partire implicitamente."],
        ["Accesso negato fail-closed; ogni comando consentito produce un audit completo e un risultato rileggibile."],
    ),
    3: page(
        ["viste aggregate dei registri canonici", "stato importazioni e riconciliazioni", "anno globale"],
        ["Nessuna scrittura contabile; solo preferenze di visualizzazione non sensibili."],
        [
            "Caricare anno e permessi, poi KPI calcolati dai registri e non da valori salvati nella pagina.",
            "Ogni KPI deve dichiarare formula, periodo, ultimo aggiornamento e stato della fonte.",
            "Il clic su una card apre la lista esatta che compone il numero, con gli stessi filtri.",
        ],
        ["Aggiornamento periodico read-only e invalidazione quando termina un'importazione."],
        ["KPI verso Fatture, Prima Nota, Riconciliazioni, Scadenze e anomalie filtrate."],
        ["Errore o fonte indisponibile non diventano zero; totali di documenti, pagamenti e saldi restano semanticamente distinti."],
        ["Somma delle righe di drill-down uguale alla card al centesimo; cambio anno aggiorna card e destinazione."],
    ),
    4: page(
        ["anno globale", "anagrafiche fornitori/dipendenti", "categorie e metodi consentiti"],
        ["movimento o documento nel registro canonico scelto tramite il writer di dominio"],
        [
            "L'utente sceglie prima il tipo: corrispettivo, versamento, pagamento, apporto soci o presenza.",
            "Il form cambia campi e controlli in base al tipo, calcola l'anteprima e mostra registro/segno di destinazione.",
            "Il backend genera idempotency key e operation_id, salva una sola volta e restituisce il link al risultato.",
        ],
        ["Riconoscimento di un invio ripetuto e proposta di valori anagrafici già verificati."],
        ["Il risultato apre Prima Nota, Corrispettivi, Soci o Personale sulla riga appena creata."],
        ["Mai scrivere direttamente in più registri dal browser; mai assumere Cassa/Banca dal solo importo."],
        ["Doppio invio produce un solo record; segno, data, centesimi e registro coincidono con l'anteprima."],
    ),
    5: page(
        ["Documenti", "Fatture ricevute", "Fornitori", "Relazioni", "Prima Nota e movimenti bancari"],
        ["stato e classificazione fattura", "relazioni di pagamento", "eventuale destinazione Cassa/Banca richiesta"],
        [
            "Indicizzare XML/PDF con chiave fattura composta da cedente, numero, data e tipo, conservando l'originale Drive.",
            "Mostrare imponibile, IVA esposta, totale, scadenza, residuo, metodo previsto e prove collegate.",
            "Segnare pagata solo con relazione confermata a pagamento/prova coerente; altrimenti mostrare prevista, candidata o da verificare.",
            "I comandi Cassa/Banca spostano o correggono la scrittura tramite operation_id senza duplicare la fattura.",
        ],
        ["Matching certo con banca/PayPal/assegno solo usando identità, centesimi, data e provenienza; aggiornamento residui."],
        ["Viewer originale; link bidirezionali a fornitore, Prima Nota, banca, PayPal, assegno e documento."],
        ["Non dedurre il pagamento dal metodo previsto; non usare l'importo da solo; IVA esposta non equivale a IVA detraibile."],
        ["Ogni fattura appare una volta, apre l'originale e mostra la stessa relazione/stato da tutte le pagine collegate."],
    ),
    6: page(
        ["XML/ZIP corrispettivi", "Corrispettivi", "chiusure POS", "Prima Nota Cassa", "accrediti provider/banca"],
        ["giornata corrispettivi deduplicata", "scrittura vendite Cassa", "crediti POS attesi separati"],
        [
            "Validare firma/schema e ricavare data, imponibili, IVA e mezzi di pagamento dalla fonte RT.",
            "Creare una giornata canonica per dispositivo/data e ripartire contanti, carte e altri mezzi senza inventare valori mancanti.",
            "Registrare vendite/contanti in Cassa e crediti POS attesi come fatti distinti; l'accredito bancario resta prova successiva.",
            "Mostrare differenze tra RT, chiusura terminale e accredito con lista delle righe interessate.",
        ],
        ["Secondo import identico nuovi=0; sincronizzazione idempotente verso Prima Nota."],
        ["Giornata verso documento RT, Prima Nota Cassa, Coerenza POS e accrediti riconciliati."],
        ["Non trasformare una chiusura POS in vendita aggiuntiva; non confondere importo lordo, netto e commissioni."],
        ["Totali aliquote e mezzi quadrano con il documento; una nuova giornata compare automaticamente in Cassa una sola volta."],
    ),
    7: page(
        ["Fornitori", "Fatture ricevute", "pagamenti e IBAN verificati", "regole operative"],
        ["anagrafica canonica", "alias", "metodo previsto", "merge controllato"],
        [
            "Identificare il fornitore principalmente con partita IVA/codice fiscale normalizzati e mantenere denominazioni storiche come alias.",
            "Mostrare contatti, IBAN con provenienza, fatture, pagato/residuo e ultimo documento per anno.",
            "La modifica aggiorna solo l'anagrafica; il merge presenta anteprima di tutte le relazioni e conserva l'identità assorbita.",
        ],
        ["Aggiornamento dati da fatture nuove solo per campi con fonte più affidabile, mai sovrascrittura cieca."],
        ["Drill-down verso fatture, scadenze, pagamenti, documenti e regole di associazione."],
        ["Non cancellare un fornitore con fatti collegati; IBAN o metodo previsto non provano un pagamento."],
        ["Nessun duplicato per stessa identità fiscale; totali fatture/residui coincidono con l'archivio fatture."],
    ),
    8: page(
        [
            "Corrispettivi RT XML/ZIP da Drive o Import documenti: totale fiscale giornaliero e quota elettronica complessiva, senza attribuzione del gestore POS",
            "Numia corrente: chiusura giornaliera inserita manualmente dall'operatore; storico Numia: transazioni dell'export del gestore CSV/XLSX importato dalla cartella Drive configurata",
            "SumUp: API ufficiale transactions/history e payouts, configurata con SUMUP_API_KEY e SUMUP_MERCHANT_CODE",
            "Estratti conto Banco BPM e conto Mastercard SumUp: accrediti effettivi, commissioni, rimborsi e chargeback",
            "fatture, finanziamenti soci, versamenti contanti e relazioni operation_id",
        ],
        [
            "entrata giornaliera Cassa dal corrispettivo RT tramite writer unico",
            "uscita Cassa POS e credito Banca atteso distinti per Numia e SumUp, collegati dallo stesso operation_id",
            "trasferimenti Cassa-Banca, riconciliazioni e correzioni tracciate",
        ],
        [
            "Mostrare Cassa, Banca, SumUp e Soci come conti distinti dello stesso ledger, raggruppando tutte le operazioni in card giornaliere.",
            "Calcolare saldi progressivi dal riporto iniziale e dalle righe ordinate; ogni giorno espone numero operazioni e totale netto.",
            "Un versamento contanti crea uscita Cassa ed entrata Banca attesa con lo stesso operation_id; il movimento di estratto conto la riconcilia senza crearne una terza.",
            "Il corrispettivo RT genera l'entrata Cassa totale, ma la sua quota elettronica non può essere ripartita tra Numia e SumUp: le uscite POS si creano soltanto dai totali reali dei singoli gestori.",
            "Per Numia usare come fonte operativa la chiusura manuale serale oppure, per il pregresso, l'export transazioni del gestore; l'accredito NUMIA nell'estratto BPM è soltanto una prova finanziaria successiva, mai una vendita né la fonte dell'attesa.",
            "Per SumUp archiviare le transazioni API riuscite per giorno Europe/Rome e i payout separati; le transazioni confermano il terminale ma non creano una seconda vendita, mentre il payout riconcilia il credito sul conto Mastercard tramite riferimenti provider.",
            "Ogni gestore genera una propria uscita Cassa e un proprio credito atteso; accredito effettivo, commissione, rimborso, chargeback e movimento banca restano fatti separati ma collegati.",
            "Se arriva una fonte Numia più autorevole, confermare il valore uguale oppure aprire una differenza sul valore discordante senza sovrascrivere o duplicare silenziosamente; priorità: manuale, export Excel, terminale/API.",
            "Spostare una fattura tra Cassa e Banca corregge la scrittura esistente, conserva audit e aggiorna tutte le viste.",
        ],
        [
            "La sincronizzazione SumUp gira ogni 30 minuti e rilegge gli ultimi 30 giorni in modo idempotente; l'aggiornamento manuale può richiamare POST /api/sumup/sincronizza.",
            "L'import Drive degli export del gestore Numia instrada CSV/XLSX/XLSM al parser POS e deduplica ogni transazione per ID provider o chiave canonica.",
            "Import estratto conto idempotente; generazione automatica di attesi POS/versamenti; associazioni certe e coda dei dubbi.",
        ],
        [
            "Ogni riga apre fattura/documento/prova; operation_id consente di passare tra Cassa, Banca, SumUp, PayPal e riconciliazione.",
            "Prima Nota ↔ Coerenza POS ↔ corrispettivo RT ↔ chiusura/transazioni provider ↔ credito atteso ↔ accredito effettivo.",
        ],
        [
            "Non inserire movimenti bancari reali in Cassa; non usare saldi hardcoded; non marcare pagato senza prova coerente.",
            "Non usare l'elettronico XML RT come importo Numia o SumUp e non sommare chiusura POS, vendita RT e accredito come tre ricavi.",
            "Nessun connettore API Numia è presunto: senza chiusura manuale serale o export storico del gestore la quota Numia resta mancante, mai zero inventato.",
        ],
        [
            "Saldo per conto ricalcolabile al centesimo; versamento e POS risultano nelle sezioni corrette dopo refresh senza duplicati.",
            "Per un giorno con RT, Numia e SumUp sono presenti due uscite POS/crediti attesi distinti e la loro somma è confrontabile con l'elettronico RT senza modificare la fonte fiscale.",
            "Un secondo sync o reimport non crea righe aggiuntive e ogni accredito effettivo chiude soltanto il credito atteso documentato.",
        ],
    ),
    9: page(
        ["Prima Nota Cassa/Banca", "chiavi canoniche", "hash/import run", "audit delle correzioni"],
        ["marcatura recuperabile di copie esatte", "report di correzione e rollback"],
        [
            "Eseguire diagnosi read-only e mostrare sempre l'elenco completo dei gruppi, non solo un contatore.",
            "Distinguere copie certe, casi simili ma legittimi e incoerenze di relazione; assegni o rate ricorrenti non sono duplicati per importo.",
            "Applicare automaticamente solo la copia esatta secondo source_external_id/hash/fingerprint, conservando il record più completo.",
            "Registrare prima/dopo, motivo e comando di rollback; i casi dubbi restano visibili senza modifica.",
        ],
        ["La prevenzione duplicati agisce già in import; la pagina serve per audit e recupero, non per manutenzione ordinaria."],
        ["Ogni elemento della lista apre direttamente le righe nella Prima Nota filtrata."],
        ["Nessuna cancellazione fisica; nessuna deduplica per importo o fattura_id condiviso quando le date/strumenti sono diversi."],
        ["Anteprima e applicazione restituiscono gli stessi target; secondo passaggio trova zero copie certe e rollback ripristina la visibilità."],
    ),
    10: page(
        ["Dipendenti", "Cedolini", "Bonifici", "Movimenti bancari", "documenti paghe"],
        ["periodo cedolino", "note/descrizione persistenti", "relazioni pagamento e Prima Nota salari"],
        [
            "Conservare ogni cedolino come documento distinto anche se dipendente, mese e tipo coincidono.",
            "Per un bonifico effettuato prima del giorno 25 proporre il mese precedente; dal giorno 25 proporre il mese corrente, senza confermare se il cedolino non esiste.",
            "Mostrare per dipendente cedolini, bonifici, residui e documenti; il campo descrizione deve sopravvivere a refresh e filtri.",
            "Confermare l'associazione con identità dipendente/IBAN, periodo, importo e provenienza; i candidati multipli richiedono scelta.",
        ],
        ["Import paghe/bonifici idempotente e proposta automatica del periodo secondo la regola del giorno 25."],
        ["Cedolino ↔ dipendente ↔ bonifico ↔ movimento banca ↔ Prima Nota salari, tutti navigabili."],
        ["Importo uguale non basta; non scartare cedolini legittimi dello stesso mese; il periodo proposto non è conferma."],
        ["Dopo refresh restano periodo, nota e collegamenti; la somma riconciliata per dipendente coincide con i bonifici confermati."],
    ),
    11: page(
        ["Fatture di noleggio", "veicoli", "contratti", "storico driver", "dati automotive opzionali"],
        ["anagrafica veicolo completa", "contratto", "assegnazioni driver con intervallo", "relazioni fatture"],
        [
            "Scansionare fatture XML/PDF dei noleggiatori e ricavare targa, telaio se presente, marca/modello, contratto, periodo e costi.",
            "Unire le informazioni per targa normalizzata senza creare schede vuote; mostrare solo veicoli completi o una coda esplicita di documenti non interpretabili.",
            "Registrare l'assegnazione driver con data inizio/fine e fonte; una nuova assegnazione chiude la precedente senza cancellarla.",
            "Gli arricchimenti esterni sono proposte e non sovrascrivono dati documentali più affidabili.",
        ],
        ["Nuova fattura aggiorna veicolo/contratto/costi in modo idempotente e tenta l'associazione solo se la targa è certa."],
        ["Veicolo ↔ fatture ↔ contratto ↔ driver storico ↔ verbali ↔ costi."],
        ["Niente form manuali incompleti quando i dati sono già nelle fatture; assenza di fattura recente non è automaticamente un errore."],
        ["Ogni veicolo mostrato ha targa e fonte; fatture e driver corretti sono raggiungibili e una nuova scansione non duplica costi."],
    ),
    12: page(
        ["Verbali PartenoPay/Drive/Gmail", "veicoli", "storico driver", "pagamenti", "quietanze"],
        ["verbale canonico", "associazione veicolo/driver", "stato pagamento", "attesa quietanza"],
        [
            "Importare e leggere il PDF originale, estraendo numero, data/ora infrazione, targa, ente, trasgressore, scadenza e importo esatto.",
            "Associare automaticamente il veicolo per targa e il driver solo se l'assegnazione copre data/ora del verbale; altrimenti mostrare candidati.",
            "Accettare Ceraldi Group S.r.l. come trasgressore quando risulta dal documento, senza inventare un driver.",
            "Dopo prova di pagamento usare PAGATO - ATTESA QUIETANZA; collegare la quietanza quando arriva e mantenere distinta la prova bancaria.",
        ],
        ["Controllo Gmail giornaliero idempotente e promemoria su scadenze/quietanze mancanti."],
        ["Verbale ↔ PDF ↔ targa ↔ driver storico ↔ pagamento ↔ quietanza ↔ movimento banca."],
        ["Mai associare driver per importo; mai chiamare fattura la quietanza; originali Gmail/Drive non vengono spostati o eliminati."],
        ["Importo mostrato coincide col PDF; casi certi si completano da soli, ambigui restano nella lista con candidati e motivo."],
    ),
    13: page(
        ["veicoli", "fatture noleggio", "pedaggi", "verbali", "bolli", "riparazioni"],
        ["Nessuna scrittura primaria: vista costi derivata ed eventuali classificazioni con audit."],
        [
            "Aggregare per targa e periodo solo costi collegati da relazioni confermate.",
            "Separare canone, servizi, pedaggi, verbali, bollo, riparazioni e altri costi, mostrando documento e formula.",
            "Consentire drill-down da ogni totale alle righe origine e confronto tra veicoli/periodi omogenei.",
        ],
        ["Ricalcolo della vista quando arriva o cambia una relazione documentale."],
        ["Costo ↔ veicolo ↔ fattura/documento ↔ eventuale pagamento e Prima Nota."],
        ["Non duplicare lo stesso costo presente in fattura e pagamento; un pagamento non è una nuova componente di costo."],
        ["Somma categorie uguale al totale veicolo e ogni centesimo è spiegato da una riga origine."],
    ),
    14: page(
        ["verbale identificato dalla route", "PDF e metadati", "relazioni veicolo/driver/pagamento/quietanza"],
        ["correzioni verificate", "associazioni manuali esplicite", "richiesta nuova lettura OCR"],
        [
            "Risolvere l'identificativo in un solo verbale oppure mostrare 404 utile senza creare record fittizi.",
            "Mostrare numero, date, ente, targa, trasgressore, driver, importo, scadenze e stato con fonte per campo.",
            "Aprire il PDF in un viewer chiudibile e accessibile; permettere associa PDF quando l'originale manca o è errato.",
            "Una correzione manuale richiede motivo, conserva il valore OCR precedente e rilancia i controlli collegati.",
        ],
        ["Ricalcolo candidati driver e prove dopo nuova lettura o nuovo documento."],
        ["Collegamenti diretti a veicolo, driver, pagamento, quietanza, banca e lista verbali."],
        ["Non sostituire il dato del PDF senza provenienza; associazioni ambigue non diventano definitive."],
        ["Il fascicolo ricostruisce tutta la storia del verbale e il viewer si apre/chiude senza lasciare overlay bloccanti."],
    ),
    15: page(
        ["piano dei conti versionato", "regole di classificazione", "scritture e righe giornale"],
        ["conto/sottoconto", "validità temporale", "regole approvate"],
        [
            "Mostrare la gerarchia con codice stabile, natura Dare/Avere, validità e conti non più utilizzabili separati.",
            "Creazione/modifica controlla unicità, cicli gerarchici e impatto sulle regole future.",
            "La disattivazione impedisce nuove scritture ma conserva storico e bilanci precedenti.",
        ],
        ["Suggerire classificazioni dalle regole approvate senza riclassificare automaticamente periodi chiusi."],
        ["Conto ↔ movimenti giornale ↔ documenti/fatture ↔ bilancio e controlli."],
        ["Mai cancellare conti usati; nessuna riclassificazione retroattiva silenziosa."],
        ["Gerarchia senza cicli; ogni saldo apre le scritture origine e un conto disattivato resta nello storico."],
    ),
    16: page(
        ["scritture giornale valide", "piano dei conti", "periodo/anno globale"],
        ["Nessuna scrittura primaria; eventuale snapshot firmato solo come report."],
        [
            "Calcolare Stato patrimoniale e Conto economico dalle righe bilanciate e dai conti validi nel periodo.",
            "Mostrare saldi iniziali, movimenti, saldi finali e quadratura Dare/Avere con formule esplicite.",
            "Ogni riga consente drill-down al conto, alla scrittura e al documento origine.",
        ],
        ["Ricalcolo read-only quando cambiano scritture aperte; periodi chiusi usano la versione approvata."],
        ["Bilancio ↔ piano conti ↔ giornale ↔ documento/prova origine."],
        ["Non usare totali Prima Nota non contabilizzati come bilancio; errore fonte non diventa zero."],
        ["Dare uguale Avere e utile/perdita riconciliabile al centesimo con il giornale."],
    ),
    17: page(
        ["bilancio calcolato", "giornale", "piano conti", "check di quadratura"],
        ["stato e nota di risoluzione dell'anomalia, senza alterare direttamente la contabilità"],
        [
            "Eseguire controlli riproducibili: sbilanci, conti mancanti, date fuori periodo, duplicati e saldi incoerenti.",
            "Ogni alert mostra severità, regola, elenco righe, differenza e percorso di correzione.",
            "La risoluzione viene riconosciuta ricalcolando la regola, non nascondendo manualmente l'alert.",
        ],
        ["Ricalcolo dopo modifica di scritture e prima di chiusura esercizio."],
        ["Alert ↔ conto ↔ scrittura ↔ documento origine ↔ checklist di chiusura."],
        ["Contatori sempre cliccabili; nessuna correzione contabile direttamente dalla card di allerta."],
        ["Ogni anomalia è riproducibile e scompare solo quando la condizione non esiste più."],
    ),
    18: page(
        ["scritture giornale", "righe Dare/Avere", "piano conti", "documenti e operation_id"],
        ["scritture manuali bilanciate", "storni e rettifiche, mai sovrascrittura dello storico"],
        [
            "Assegnare numero progressivo per esercizio solo al momento della registrazione valida.",
            "Mostrare data competenza/registrazione, causale, righe Dare/Avere, stato e documento origine.",
            "Le rettifiche creano nuove scritture collegate; export conserva filtri, numerazione e totali.",
        ],
        ["Generazione dal writer contabile unico dopo eventi di dominio confermati."],
        ["Scrittura ↔ evento/fattura/pagamento/F24 ↔ piano conti ↔ bilancio."],
        ["Una scrittura sbilanciata o priva di conto valido non può essere registrata; progressivi non si riciclano."],
        ["Per ogni scrittura Dare=Avere e sequenza progressiva senza duplicati; storno navigabile in entrambe le direzioni."],
    ),
    19: page(
        ["KPI mensili", "Prima Nota", "corrispettivi/POS", "fatture", "F24", "giornale"],
        ["stato controllo, assegnatario e nota; nessuna scrittura contabile diretta"],
        [
            "Eseguire la checklist del mese con regole versionate e mostrare superato, anomalia o fonte mancante.",
            "Ogni contatore apre l'elenco esatto e mantiene anno/mese/sezione nel link.",
            "Consentire presa in carico e nota, ma chiudere il controllo solo dopo ricalcolo positivo o eccezione motivata.",
        ],
        ["Ricalcolo schedulato e dopo import rilevanti; notifiche soltanto su anomalie persistenti."],
        ["Controllo ↔ pagina operativa esatta ↔ righe origine ↔ audit risoluzione."],
        ["Niente pulsanti generici di pulizia; nessun alert senza lista e criterio."],
        ["Tutti i controlli hanno fonte e risultato riproducibile; stato mensile coincide con i dettagli."],
    ),
    20: page(
        ["scadenze fiscali", "F24", "dichiarazioni", "quietanze", "atti e notifiche"],
        ["stato operativo, promemoria e relazione al documento; non il pagamento"],
        [
            "Generare scadenze da regole versionate e documenti effettivi, indicando fonte e periodo.",
            "Mostrare per data: adempimento, importo se noto, stato, documento, responsabile e promemoria.",
            "Completato richiede prova prevista dal tipo: invio, F24, quietanza o altra evidenza, senza confonderle.",
        ],
        ["Promemoria configurabili e aggiornamento quando arriva una prova; mai invio/pagamento automatico."],
        ["Scadenza ↔ F24/dichiarazione/atto ↔ quietanza ↔ eventuale movimento banca."],
        ["Non inventare importi o scadenze da OCR incerto; fonte assente resta da verificare."],
        ["Ogni scadenza apre la prova e il calendario distingue scaduto, imminente, completato e da verificare."],
    ),
    21: page(
        ["fatture cespitabili", "cespiti", "categorie e aliquote", "documenti origine"],
        ["scheda cespite", "piano ammortamento", "dismissione", "scritture collegate"],
        [
            "Proporre cespiti da fatture con criteri espliciti; l'utente conferma categoria, data entrata in funzione e quota detraibile.",
            "Calcolare ammortamenti con Decimal, pro-rata e versione delle regole, mostrando piano completo.",
            "Registrazione e dismissione generano eventi contabili tramite writer unico e conservano documento/fonte.",
        ],
        ["Scansione nuove fatture idempotente e verifica annuale tra piano e scritture."],
        ["Cespite ↔ fattura/PDF ↔ piano rate ↔ scritture giornale ↔ bilancio."],
        ["Non capitalizzare automaticamente per parola/importo; non modificare rate di esercizi chiusi senza rettifica."],
        ["Costo storico, fondo, quota e residuo quadrano al centesimo; ogni cespite ha documento e data di entrata in funzione."],
    ),
    22: page(
        ["saldi banca/cassa", "crediti/debiti", "mutui", "finanziamenti soci", "scadenze"],
        ["Nessuna scrittura primaria; classificazioni finanziarie tracciate quando necessarie."],
        [
            "Calcolare liquidità, posizione finanziaria netta e flussi da registri confermati con periodo e formula visibili.",
            "Separare finanziamenti soci da ricavi e distinguere capitale, interessi, debiti e crediti.",
            "Ogni totale apre strumenti e movimenti che lo compongono, senza sommare la stessa operazione su più viste.",
        ],
        ["Ricalcolo derivato quando cambiano saldi, rate o relazioni."],
        ["Indicatore ↔ banca/Prima Nota ↔ mutuo/socio ↔ documento e scadenza."],
        ["Niente saldi inventati o cache non datata; trasferimenti interni non sono flussi economici."],
        ["Ogni indicatore è riconciliabile alle fonti e finanziamenti soci non risultano duplicati tra banca e ledger."],
    ),
    23: page(
        ["check mensili", "bilancio", "giornale", "IVA/F24", "stato esercizio"],
        ["evento di chiusura", "snapshot e hash", "eventuale riapertura/rettifica"],
        [
            "Eseguire una checklist bloccante di quadrature, periodi, documenti e registrazioni mancanti.",
            "Mostrare anteprima completa degli effetti e richiedere frase esatta più step-up authentication.",
            "La chiusura congela la versione, registra hash/attore/orario e impedisce modifiche dirette al periodo.",
            "La riapertura è separata, motivata e auditata; le rettifiche non cancellano lo snapshot precedente.",
        ],
        ["Ricalcolo della checklist prima della conferma e invalidazione se i dati cambiano."],
        ["Chiusura ↔ bilancio ↔ giornale ↔ controlli ↔ audit e snapshot esportabile."],
        ["Nessuna chiusura automatica o con checklist rossa; nessuna cancellazione di dati originari."],
        ["Chiusura impossibile senza conferma forte; esercizio chiuso produce lo stesso snapshot da sorgenti immutate."],
    ),
    24: page(
        ["budget versionato", "piano conti/centri", "consuntivo giornale", "anno globale"],
        ["versione budget, righe mensili, note e stato approvazione"],
        [
            "Creare scenari separati per anno/versione senza sovrascrivere quello approvato.",
            "Inserire importi per mese, conto/voce e centro; mostrare totale e controlli di coerenza.",
            "Confrontare consuntivo omogeneo con budget e aprire il dettaglio dello scostamento.",
        ],
        ["Duplicazione anno crea una bozza distinta e conserva provenienza/versione."],
        ["Budget ↔ conto/centro ↔ consuntivo giornale ↔ utile obiettivo/previsioni."],
        ["Budget e simulazioni non generano scritture reali; una versione approvata non si modifica in silenzio."],
        ["Totali mensili/annuali coerenti e scostamento uguale a consuntivo meno budget al centesimo."],
    ),
    25: page(
        ["contratti mutuo/PDF", "mutui", "piano rate", "movimenti bancari", "giornale"],
        ["mutuo e rate", "relazione rata-movimento", "scritture capitale/interessi"],
        [
            "Importare o inserire contratto con banca, capitale, tasso, decorrenza e piano verificabile.",
            "Per ogni rata separare quota capitale, interessi, spese e residuo; mostrare scadenza e stato.",
            "Riconciliare il movimento bancario alla rata usando riferimento, data e importo, poi generare la scrittura tramite writer unico.",
        ],
        ["Proposta automatica di rata candidata e aggiornamento residuo dopo conferma."],
        ["Mutuo ↔ contratto/PDF ↔ rata ↔ banca ↔ giornale ↔ posizione finanziaria."],
        ["Importo uguale non basta; non contabilizzare l'intera rata come costo; nessun pagamento automatico."],
        ["Somma capitale rimborsato più residuo coincide col capitale; rata riconciliata apre il movimento esatto."],
    ),
    26: page(
        ["viste contabili derivate", "giornale", "piano conti", "periodi e dimensioni"],
        ["Nessuna scrittura; preferenze/report eventualmente salvati."],
        [
            "Presentare analisi per conto, mese, fornitore e centro usando formule documentate.",
            "Applicare gli stessi filtri canonici del bilancio e indicare dati esclusi o incompleti.",
            "Ogni grafico/tabella offre drill-down alle righe contabili e export con metadati del filtro.",
        ],
        ["Ricalcolo read-only; cache con data/fingerprint e invalidazione esplicita."],
        ["Analisi ↔ giornale ↔ conto ↔ documento origine."],
        ["Nessun indicatore senza formula; errore fonte non diventa zero; niente scritture dalla vista analitica."],
        ["Totali delle analisi coincidono con il giornale filtrato e ogni dato è spiegabile."],
    ),
    27: page(
        ["consuntivi", "budget", "costi/ricavi ricorrenti", "parametri utente"],
        ["scenario di simulazione separato, mai scritture o budget approvati"],
        [
            "Partire da un periodo/base dichiarato e permettere ipotesi su ricavi, margini, costi e imposte.",
            "Calcolare il fatturato/margine necessario all'utile obiettivo con formule e sensibilità visibili.",
            "Salvare o confrontare scenari nominati senza mescolarli ai consuntivi.",
        ],
        ["Aggiornamento immediato della simulazione nel browser o servizio read-only."],
        ["Scenario ↔ budget/consuntivo usato come base, con link ma senza relazione contabile."],
        ["Nessuna scrittura, ordine o pagamento; risultati sono simulazioni e devono essere etichettati."],
        ["Stessi input producono stesso risultato; esportazione riporta tutte le ipotesi e la data base."],
    ),
    28: page(
        ["storico acquisti", "fatture/scadenze", "budget", "fornitori", "parametri previsionali"],
        ["scenario/previsione e note, non ordini o scritture"],
        [
            "Costruire la base da fatture confermate e periodicità riconoscibili, escludendo duplicati e storni.",
            "Mostrare per fornitore/mese importo previsto, intervallo, motivazione e dati storici utilizzati.",
            "Consentire correzioni di scenario e confronto con budget/consuntivo.",
        ],
        ["Ricalcolo periodico delle proposte con versione del modello e confidenza."],
        ["Previsione ↔ fatture storiche ↔ fornitore ↔ budget e scadenze."],
        ["Non creare ordini, pagamenti o fatture; valori con storico insufficiente restano non stimati."],
        ["Ogni previsione espone la serie origine e la somma per periodo è riproducibile."],
    ),
    29: page(
        ["casi riconciliati e rifiutati", "regole approvate", "feature/provenienza del suggerimento"],
        ["suggerimento, confidenza, approvazione/revoca e versione regola"],
        [
            "Generare suggerimenti spiegando segnali, esempi, perimetro e confidenza.",
            "L'utente approva, rifiuta o limita la regola; l'approvazione non modifica retroattivamente record già chiusi.",
            "Ogni applicazione futura registra regola/versione e resta revocabile o correggibile.",
        ],
        ["Training solo su decisioni confermate e dati minimizzati; monitoraggio falsi positivi."],
        ["Suggerimento ↔ esempi origine ↔ regola ↔ record sui quali è stata applicata."],
        ["Nessun auto-apprendimento da associazioni ambigue; nessuna regola opaca o pagamento automatico."],
        ["Regola approvata applicata solo nel perimetro; revoca impedisce nuove applicazioni e mantiene audit storico."],
    ),
    30: page(
        ["fatture e note credito", "pagamenti confermati/parziali", "fornitori", "scadenze"],
        ["scadenza, sollecito/promemoria interno, relazione a pagamento"],
        [
            "Calcolare residuo per fattura da totale meno pagamenti confermati e note credito compatibili.",
            "Raggruppare per fornitore e scadenza, distinguendo previsto, scaduto, parziale, pagato e da verificare.",
            "Ogni alert apre le fatture esatte; l'utente può annotare o associare una prova, non forzare il saldo senza evidenza.",
        ],
        ["Aggiornamento automatico quando fattura/pagamento cambia e promemoria sulle scadenze effettive."],
        ["Scadenza ↔ fattura ↔ fornitore ↔ pagamento/prova ↔ Prima Nota."],
        ["Metodo previsto o disposizione non azzerano il residuo; importo simile non associa automaticamente."],
        ["Residui sommati coincidono con archivio fatture e ogni stato apre le prove che lo giustificano."],
    ),
    31: page(
        ["fatture/compensi con ritenuta", "percipienti", "F24 e codici tributo", "quietanze"],
        ["ritenuta per documento/periodo", "relazioni F24", "stato versamento documentale/bancario"],
        [
            "Estrarre base, aliquota, importo, causale e percipiente dalla fattura o inserimento verificato.",
            "Aggregare per periodo/codice tributo mantenendo sempre il legame alle singole ritenute.",
            "Collegare modello F24 e quietanza come prove distinte; pagato banca richiede movimento compatibile.",
        ],
        ["Proposta del codice tributo da regole fiscali versionate e controllo quadratura annuale."],
        ["Ritenuta ↔ fattura ↔ percipiente ↔ riga F24 ↔ PDF ↔ quietanza ↔ banca."],
        ["Non creare F24 dal solo totale; non trattare quietanza come movimento bancario."],
        ["Somma ritenute per codice/periodo coincide con righe F24 collegate e differenze sono elencate."],
    ),
    32: page(
        ["casi di riconciliazione di banca, F24, stipendi, documenti, assegni, PayPal e PagoPA"],
        ["Nessuna associazione diretta dalla dashboard; solo filtri/priorità del caso."],
        [
            "Mostrare code per dominio con conteggi calcolati e stato fonte/ultimo aggiornamento.",
            "Ogni card apre la lista esatta mantenendo anno, stato e filtro.",
            "Separare certi auto-risolti, candidati da scegliere, fonti mancanti e conflitti.",
        ],
        ["Aggiornamento dopo import o decisione; priorità per scadenza/severità, non per numero casuale."],
        ["Dashboard ↔ pagina dominio ↔ singolo caso ↔ prove e relazioni."],
        ["Nessun contatore non navigabile; nessuna conferma massiva di casi ambigui."],
        ["Conteggi dashboard uguali alle liste e tornano a zero solo quando i casi sono realmente risolti."],
    ),
    33: page(
        ["movimenti bancari immutabili", "fatture", "Prima Nota", "PayPal/assegni/bonifici/F24/PagoPA"],
        ["caso/candidati", "relazione confermata", "scrittura contabile tramite writer unico"],
        [
            "Importare ogni riga con fingerprint di banca/conto/data/importo/causale/riferimento e non modificarne il contenuto originale.",
            "Generare candidati con motivazione: identità, riferimenti, centesimi, finestra data e provenienza; mostrare punteggio per criterio.",
            "Confermare automaticamente solo una corrispondenza univoca e forte; altrimenti Scegli fattura/entità o classifica senza documento.",
            "Assegnare lo stesso operation_id alle prove dello stesso evento mantenendo record distinti e collegamenti reciproci.",
        ],
        ["Nuovo estratto riprocessa solo righe nuove e tenta nuovamente i casi aperti senza duplicare relazioni."],
        ["Movimento ↔ caso ↔ fattura/PayPal/assegno/F24/bonifico ↔ Prima Nota e documento."],
        ["Mai associare per importo solo; commissione ignorata è riconciliazione classificata, non pagamento fattura."],
        ["Secondo import nuovi=0; ogni conferma è visibile in entrambe le pagine e l'importo resta al centesimo."],
    ),
    34: page(
        ["F24 unificato", "righe tributo", "PDF", "Quietanze F24", "movimenti bancari", "codici tributo"],
        ["relazioni F24-quietanza-banca", "stato per modello e riga tributo"],
        [
            "Mostrare tutti i modelli, non solo pendenti, con periodo, totale e PDF originale.",
            "Espandere le righe per sezione/codice/periodo/debito/credito e permettere ricerca codice tributo → F24 → PDF e percorso inverso.",
            "Collegare quietanza solo con codici, periodi e importi compatibili; indicare QUIETANZA PRESENTE - BANCA DA VERIFICARE finché manca il movimento.",
            "Il pagamento bancario confermato aggiorna il modello senza fondere F24, quietanza e movimento.",
        ],
        ["Import da Drive/Gmail/Import documenti idempotente e nuovo tentativo di riconciliazione su evidenze aggiunte."],
        ["Codice tributo ↔ riga F24 ↔ PDF ↔ quietanza ↔ banca ↔ dichiarazione compatibile."],
        ["Non ricostruire un F24 dalla sola quietanza; non mostrare pagato banca senza movimento; crediti e debiti conservano segno."],
        ["Ogni F24 Drive compare nella pagina, ricerca bidirezionale funziona e somme righe quadrano col totale documento."],
    ),
    35: page(
        ["Cedolini", "Dipendenti/IBAN", "Bonifici", "Movimenti bancari", "Prima Nota salari"],
        ["candidati periodo/dipendente", "relazioni confermate e stato pagamento"],
        [
            "Partire dal bonifico o movimento e identificare il dipendente con beneficiario/IBAN normalizzati.",
            "Proporre periodo precedente se data <25, stesso mese se data ≥25; il periodo resta visibile dopo refresh.",
            "Verificare importo e documenti disponibili, mantenere più cedolini legittimi e chiedere scelta se più candidati.",
        ],
        ["Riprocessare casi aperti quando arriva il cedolino del mese corrente."],
        ["Bonifico ↔ movimento banca ↔ dipendente ↔ cedolino ↔ Prima Nota salari/PDF."],
        ["La regola del giorno 25 propone, non conferma; importo solo o nome parziale non bastano."],
        ["Periodo/descrizione persistono; pagamento confermato apre cedolino e banca in entrambe le direzioni."],
    ),
    36: page(
        ["Documenti inbox/Drive", "classificazioni", "entità candidate", "relazioni"],
        ["classificazione approvata", "relazione documento-entità", "stato elaborazione"],
        [
            "Mostrare originale, hash, fonte, parser/versione, campi estratti e confidenza.",
            "Proporre tipo ed entità compatibili spiegando i criteri; scelta manuale disponibile per candidati ambigui.",
            "Dopo conferma invocare il servizio di dominio del tipo, conservare documento originale e link al record creato.",
        ],
        ["Auto-classificazione soltanto oltre soglia e con identità univoca; retry per errori tecnici senza duplicare."],
        ["Documento ↔ record elaborato ↔ relazioni/prove ↔ pagina dominio."],
        ["OCR basso, PDF cifrato o fonte incompleta restano in revisione; mai creare record contabile da contenuto ambiguo."],
        ["Ogni documento ha stato e destinazione; secondo processamento non crea una seconda entità."],
    ),
    37: page(
        ["bonifici importati", "movimenti bancari", "dipendenti/fatture", "note e periodi"],
        ["descrizione e periodo persistenti", "relazioni salario/fattura/banca"],
        [
            "Indicizzare data, importo, ordinante, beneficiario, IBAN, CRO/TRN e causale senza perdere il testo originale.",
            "Mostrare da associare e associati, con campo descrizione/nota modificabile e persistente.",
            "Associa salario applica la regola del giorno 25; associa fattura usa identità/provenienza e candidati motivati.",
        ],
        ["Riconciliazione automatica al movimento estratto conto quando CRO/TRN o identità forte sono univoci."],
        ["Bonifico ↔ movimento banca ↔ fattura oppure dipendente/cedolino ↔ Prima Nota."],
        ["Nessuna associazione definitiva per stesso importo; bonifici ricorrenti distinti non sono duplicati."],
        ["Nota e periodo restano dopo reload; contatori e liste coincidono e ogni associato apre le prove."],
    ),
    38: page(
        ["assegni", "movimenti bancari", "fatture", "documenti/prove"],
        ["stato assegno", "relazioni a una o più fatture", "incasso/addebito bancario confermato"],
        [
            "Identificare ogni assegno con numero completo, conto, data emissione/incasso, importo e beneficiario.",
            "Consentire associazione a una o più fatture con somma controllata e prova del documento.",
            "Il movimento bancario chiude l'assegno solo se numero/riferimento, importo e contesto sono coerenti.",
            "Gli alert mostrano la lista esatta dei candidati o delle differenze.",
        ],
        ["Ricostruzione del numero completo da finale solo come candidato; dedup su identità strumento, non fattura condivisa."],
        ["Assegno ↔ fatture ↔ movimento banca ↔ Prima Nota ↔ documento."],
        ["Assegni diversi con stesso importo o fattura non sono copie; emissione/disposizione non prova l'addebito."],
        ["Ogni assegno resta distinto e navigabile; somma fatture compatibile e stato banca supportato dal movimento esatto."],
    ),
    39: page(
        ["transazioni PayPal", "movimenti bancari SDD PayPal", "fatture", "Prima Nota"],
        ["relazioni transazione-fattura-banca", "stato riconciliazione", "note"],
        [
            "Importare tutte le transazioni con transaction ID, data, controparte, valuta, lordo, commissione e netto.",
            "Collegare fattura usando controparte/numero/data/centesimi e il movimento bancario usando riferimenti SDD PayPal e finestra coerente.",
            "Assegnare un operation_id comune a fattura, transazione e banca senza fondere le tre righe.",
            "Applicare la stessa logica a tutti i movimenti PayPal; i dubbi mostrano candidati e scelta.",
        ],
        ["Sync incrementale idempotente e riprocessamento dei non associati quando arriva fattura o banca."],
        ["PayPal ↔ fattura/PDF ↔ banca ↔ Prima Nota; ogni colonna è un link alla prova."],
        ["Non confrontare USD ed EUR senza cambio/prova; commissione e acquisto non sono la stessa riga; importo solo non basta."],
        ["Un acquisto PayPal con fattura e addebito SDD produce tre record collegati con lo stesso operation_id; il secondo sync non duplica transazioni."],
    ),
    40: page(
        [
            "Corrispettivi RT XML: quota elettronica fiscale complessiva, non separabile per gestore",
            "Numia: chiusure manuali/batch ed export ufficiali Banco BPM CSV/XLSX con transazioni, terminale, MID e punto vendita",
            "SumUp API: transazioni riuscite e payout con identificativi provider, commissioni, rimborsi e chargeback",
            "Estratti conto Banco BPM e Mastercard SumUp con accrediti effettivi e causale integrale",
            "crediti POS attesi e relazioni della Prima Nota",
        ],
        [
            "chiusure Numia inserite esplicitamente dall'utente e casi di differenza auditati",
            "relazioni confermate tra giorno POS, credito atteso e accredito effettivo",
            "nessuna nuova vendita durante i controlli o il semplice aggiornamento della pagina",
        ],
        [
            "Fase 0 - Provenienza: indicare per ogni giorno se il corrispettivo è XML definitivo, provvisorio o mancante e mostrare file/hash/import run.",
            "Fase 1 - Coerenza fiscale-operativa: confrontare l'elettronico RT complessivo con Numia reale più SumUp reale. Il confronto è informativo, non modifica né l'XML né i totali terminale; un circuito mancante rende il totale parziale, non vale zero.",
            "Fase 2 Numia - Coerenza finanziaria: confrontare il lordo reale Numia con gli accrediti lordi Banco BPM; ricavare il giorno vendita dalla causale NUMIA con riferimento DEL gg/mm/aa quando presente, perché data contabile e competenza possono differire per weekend e festività.",
            "Fase 2 SumUp - Coerenza finanziaria: confrontare le transazioni reali con i payout netti sul conto Mastercard, collegando tramite transaction code/riferimenti provider e mantenendo commissioni, rimborsi e chargeback separati.",
            "Mostrare per giorno e terminale lordo, commissioni, netto, date di competenza/accredito, differenze, record mancanti, fonti duplicate e l'elenco completo delle operazioni.",
            "Riconciliare accrediti uno-a-uno o molti-a-uno solo quando il provider lo documenta, conservando tutti gli ID e lo stesso operation_id della catena contabile.",
            "Il pulsante Aggiorna ricarica soltanto GET /api/pos-corrispettivi/verifica-coerenza, riepilogo-mensile, controllo-due-fasi e /api/sumup/riepilogo; scrive soltanto l'inserimento esplicito della chiusura Numia singola/batch o del corrispettivo serale provvisorio.",
        ],
        [
            "SumUp viene sincronizzato via API rileggendo la finestra configurata; Numia corrente si aggiorna dalla chiusura terminale manuale e lo storico dall'import Drive degli export del gestore.",
            "Il caso viene ricalcolato e riaperto se cambia una fonte; il riepilogo SumUp della pagina è una lettura dell'archivio e non chiama la rete.",
        ],
        [
            "Giorno POS ↔ corrispettivo RT ↔ chiusura/transazioni provider ↔ credito atteso ↔ payout/accredito e commissione ↔ Prima Nota.",
            "Ogni contatore o differenza apre le righe e le prove specifiche, comprese le causali bancarie e gli identificativi provider.",
        ],
        [
            "Non creare vendite dalle chiusure o dagli accrediti; data vendita e data accredito non devono coincidere per forza.",
            "Non attribuire l'elettronico RT a Numia per differenza e non usare il solo importo per collegare un payout.",
            "Le commissioni Numia seguono fattura/ciclo separato; per SumUp fanno parte del dettaglio payout e non riducono il lordo delle vendite.",
            "Le operazioni read-only della pagina non scrivono Prima Nota; una scrittura avviene soltanto tramite il servizio contabile canonico dopo un evento esplicito e idempotente.",
        ],
        [
            "Ogni differenza è spiegata con lista, fonte e formula; nei giorni completi l'elettronico RT è confrontabile con Numia più SumUp al centesimo.",
            "Per Numia il totale lordo si riconcilia agli accrediti BPM documentati; per SumUp lordo meno commissioni e rettifiche quadra con il payout netto.",
            "Aggiorna senza modifiche restituisce gli stessi record; un reimport o sync non duplica transazioni, crediti o accrediti.",
        ],
    ),
    41: page(
        ["file/ZIP caricati", "catalogo parser", "Drive e document inbox"],
        ["originali Drive", "Documenti", "import run", "record di dominio tramite servizi"],
        [
            "Anteprima identifica file, tipo probabile, hash, duplicati certi, parser e problemi senza scrivere.",
            "Il comando principale deve caricare e salvare davvero: espandere ZIP in sicurezza, archiviare originali e processare ogni elemento.",
            "Instradare F24, quietanze, fatture, corrispettivi, estratti, cedolini e altri tipi ai servizi canonici, mai a writer paralleli.",
            "Restituire report per file con nuovo/già presente/elaborato/da verificare/errore e link al risultato.",
        ],
        ["Hash e source_external_id rendono ogni reimport idempotente; corrispettivi elaborati sincronizzano Prima Nota Cassa."],
        ["Import run ↔ originale Drive ↔ documento inbox ↔ entità creata ↔ eventuale Prima Nota/riconciliazione."],
        ["Protezione ZIP traversal/bombe; nessun 'carica senza salvare'; un errore non annulla i file validi né elimina originali."],
        ["Reimport dello stesso ZIP: nuovi=0; ogni file ha esito e i corrispettivi validi compaiono una volta in Cassa."],
    ),
    42: page(
        ["indice Documenti", "metadati Drive", "relazioni a entità", "stato elaborazione"],
        ["metadati/etichette controllate", "richiesta di riprocessamento", "nessuna modifica all'originale"],
        [
            "Elencare con paginazione server, ricerca e filtri per tipo, periodo, stato, fonte e relazione.",
            "Mostrare nome, MIME, hash, percorso/provenienza, parser, data e destinazione elaborata.",
            "Aprire PDF/XML nel viewer appropriato e navigare al record collegato; il riprocessamento crea un run auditato.",
        ],
        ["Indicizzazione incrementale Drive con watermark e aggiornamento metadati senza duplicare hash."],
        ["Documento ↔ Drive originale ↔ import run ↔ fattura/F24/verbale/atto/altro record."],
        ["Nessuna eliminazione/spostamento automatico; stesso hash in cartelle di ciclo vita può essere provenienza valida."],
        ["Ricerca trova il documento e apre originale/record; conteggi filtri coerenti con paginazione."],
    ),
    43: page(
        ["risultati di controlli versionati", "registri canonici", "stato risoluzioni"],
        ["presa in carico, nota, eccezione motivata e audit"],
        [
            "Presentare controlli per severità/dominio con regola, query/versione, data e fonte.",
            "Ogni badge/numero apre la lista esatta delle righe e il collegamento alla pagina operativa corretta.",
            "Dopo una correzione rieseguire la regola; l'utente può documentare un'eccezione, non cancellare l'evidenza.",
        ],
        ["Esecuzione schedulata e dopo import; dedup degli alert sulla stessa regola/entità."],
        ["Controllo ↔ entità/righe origine ↔ azione correttiva ↔ audit della risoluzione."],
        ["Nessun alert solo numerico; nessun comando distruttivo generico; errore tecnico separato da anomalia dati."],
        ["Ogni alert è navigabile e riproducibile; contatori coincidono con liste dopo refresh."],
    ),
    44: page(
        ["movimenti bancari originali", "classificazioni", "candidati entità", "operation_id"],
        ["classificazione e relazione, mai modifica della riga bancaria originale"],
        [
            "Mostrare data valuta/contabile, segno, centesimi, causale integrale e identificatori bancari.",
            "Consentire classificazione senza documento oppure scelta fra fattura, cedolino, F24, socio, assegno, PayPal e altro.",
            "Mostrare perché ogni candidato è proposto; la conferma aggiorna relazioni e writer contabile una sola volta.",
        ],
        ["Classificazione certa da riferimenti bancari amministrabili; le regole sono versionate e revocabili."],
        ["Movimento ↔ estratto/import run ↔ entità ↔ Prima Nota/giornale."],
        ["Mai troncare causale o sovrascrivere il movimento; mai associare per importo solo."],
        ["Classificazione resta dopo refresh e apre l'entità; una seconda conferma non crea altra scrittura."],
    ),
    45: page(
        ["registri contabili/fiscali", "documenti Drive", "quadrature e periodo selezionato"],
        ["fascicolo/export immutabile con manifest, non modifiche ai dati origine"],
        [
            "Selezionare esercizio/periodo e mostrare checklist dei registri e documenti inclusi/mancanti.",
            "Generare struttura navigabile con file, indici, totali e SHA-256, preservando identificatori come testo.",
            "Bloccare l'export se quadrature essenziali falliscono oppure etichettarlo chiaramente come bozza incompleta.",
        ],
        ["Rigenerazione deterministica dello stesso fascicolo e report differenze rispetto alla versione precedente."],
        ["Indice export ↔ registro ↔ riga ↔ documento originale; manifest bidirezionale."],
        ["Nessun dato inventato, segreto o duplicato; export non modifica né sposta Drive."],
        ["ZIP/fascicolo integro, una radice, hash validi, totali uguali alle fonti e documenti apribili."],
    ),
    46: page(
        ["scadenze e anomalie", "atti/documenti", "utenti/assegnatari", "notifiche"],
        ["attività, assegnazione, stato, nota e promemoria"],
        [
            "Creare attività da evento reale o manuale indicando fonte, scadenza, responsabile e risultato atteso.",
            "Mostrare agenda/lista con priorità spiegata e link al documento o caso originario.",
            "Completare solo con nota o prova richiesta; rinvio e riassegnazione restano nell'audit.",
        ],
        ["Promemoria idempotenti; evitare notifiche duplicate per stesso evento/scadenza."],
        ["Attività ↔ scadenza/alert/documento ↔ responsabile ↔ notifica e audit."],
        ["Nessuna operazione esterna o pagamento automatico; una notifica inviata non completa l'attività."],
        ["Ogni attività ha fonte e proprietario; promemoria una sola volta per finestra configurata."],
    ),
    47: page(
        ["soggetti/fornitori", "visure già archiviate", "metadati e scadenza documento"],
        ["richiesta preparata o documento visura importato; nessun acquisto automatico"],
        [
            "Ricercare soggetto e mostrare visure esistenti con tipo, data, fonte, validità e PDF.",
            "Una nuova richiesta prepara parametri/costo e richiede conferma separata nel provider autorizzato.",
            "Il documento ricevuto viene archiviato e collegato al soggetto conservando protocollo/hash.",
        ],
        ["Promemoria di scadenza; nessuna chiamata a pagamento senza azione esplicita."],
        ["Visura ↔ soggetto/fornitore ↔ documento Drive ↔ eventuale richiesta provider."],
        ["Non eseguire richieste esterne o addebiti automaticamente; non mostrare una richiesta come documento ricevuto."],
        ["Documenti esistenti apribili; richiesta e ricevuta hanno stati distinti e audit completi."],
    ),
    48: page(
        ["catalogo automazioni", "permessi", "run e log", "decisioni proposte"],
        ["configurazione agente", "approvazione/rifiuto proposta", "audit run"],
        [
            "Mostrare per agente scopo, trigger, fonti, permessi massimi, stato e ultimo esito.",
            "Ogni run espone input riferiti, decisioni, output, errori e modifiche proposte.",
            "Approvare significa autorizzare la proposta prevista, non pagamenti o azioni fuori scope; disattivazione immediata disponibile.",
        ],
        ["Scheduler con lock/idempotenza e circuit breaker; azioni ad alto rischio restano manuali."],
        ["Agente ↔ run ↔ record letti/proposte ↔ audit e notifiche."],
        ["Nessun accesso a segreti in UI/log; nessuna estensione autonoma dei permessi o esecuzione di pagamenti."],
        ["Run riproducibile e tracciato; agente disattivato non parte e una proposta ambigua non modifica dati."],
    ),
    49: page(
        ["configurazione query/mittenti F24", "stato connessione Gmail", "ultimo watermark/run"],
        ["query e mittenti validati", "configurazione scheduler non segreta"],
        [
            "Configurare ricerca in:anywhere, alias/wrapper PEC e tipi allegato attesi senza esporre credenziali.",
            "Testare in sola lettura mostrando messaggi trovati, pagine percorse e potenziali allegati senza importarli.",
            "Salvare configurazione versionata e mostrare ultimo run, watermark, nuovi/duplicati/errori.",
        ],
        ["Controllo giornaliero Europe/Rome con paginazione, Gmail IDs, SHA-256, lock e retry."],
        ["Configurazione ↔ run Gmail ↔ documenti F24/quietanze importati ↔ audit."],
        ["Mai spostare/eliminare/segnare lette le email; nessuna password/token restituita alla UI."],
        ["Test trova gli stessi messaggi della query completa; secondo run senza novità importa zero allegati."],
    ),
    50: page(
        ["configurazione modello/provider non sensibile", "stato secret reference", "health e limiti"],
        ["riferimenti a segreti, modello/limiti e policy; mai valore del segreto"],
        [
            "Mostrare provider, modello, timeout, limiti, finalità consentite e presenza del segreto come sì/no.",
            "Validare configurazione e fare health test minimizzato senza inviare documenti aziendali reali.",
            "Salvare versione e audit; rollback alla configurazione precedente disponibile.",
        ],
        ["Health periodico e circuit breaker su errori/costi anomali."],
        ["Configurazione ↔ run agente/AI ↔ audit, senza collegare contenuti sensibili ai log."],
        ["Nessuna chiave in codice, fogli, log, API o ZIP; AI non conferma associazioni contabili ambigue."],
        ["Secret non leggibile dalla UI; health fallito blocca l'uso ma non altera dati."],
    ),
    51: page(
        ["client API", "scope/ruoli", "OpenAPI", "rate limit e utilizzo token"],
        ["client e scope", "hash/metadata token", "revoca/rotazione e audit"],
        [
            "Creare client con scope minimo e mostrare il token una sola volta al momento della generazione.",
            "Documentare endpoint, schema, errori, idempotency e limiti dal contratto OpenAPI corrente.",
            "Rotazione crea nuova credenziale e finestra controllata; revoca è immediata e auditata.",
        ],
        ["Rate limit, scadenza e rilevamento uso anomalo lato gateway."],
        ["Client ↔ scope ↔ chiamate/audit ↔ versione OpenAPI."],
        ["Token mai persistito in chiaro o mostrato nuovamente; nessuno scope amministrativo implicito."],
        ["Client senza scope riceve 403; token revocato non funziona; OpenAPI coincide con router pubblicati."],
    ),
    52: page(
        ["avvisi PagoPA", "IUV/ente", "ricevute", "movimenti bancari", "documenti"],
        ["relazioni avviso-ricevuta-banca", "stato del caso"],
        [
            "Importare avviso e ricevuta come documenti distinti con IUV, ente, causale, importo e scadenza.",
            "Associare automaticamente ricevuta all'avviso su IUV univoco; cercare banca con riferimento/identità/importo/data.",
            "Mostrare pagato documentale e pagato banca come stati separati fino alla conferma completa.",
        ],
        ["Riprocessamento quando arriva ricevuta o movimento; notifiche su avvisi prossimi alla scadenza."],
        ["Avviso ↔ IUV ↔ ricevuta ↔ banca ↔ Prima Nota ↔ documento originale."],
        ["Nessun pagamento automatico; importo solo non basta; IUV conflittuale richiede scelta."],
        ["IUV univoco collega avviso/ricevuta; pagamento banca apre il movimento e secondo import non duplica."],
    ),
    53: page(
        ["mittenti/alias configurati", "tipi documento", "statistiche/errori ingest"],
        ["regola mittente-canale-documento, priorità e audit"],
        [
            "Registrare indirizzo/dominio, alias PEC, canale, documenti attesi e livello di affidabilità.",
            "Testare la regola su esempi esistenti in sola lettura e mostrare corrispondenze/conflitti.",
            "Versionare modifiche e permettere disattivazione senza perdere lo storico dei documenti già importati.",
        ],
        ["Le regole alimentano classificazione Gmail ma non sostituiscono hash e validazione del documento."],
        ["Mittente ↔ run Gmail ↔ documenti classificati ↔ errori/audit."],
        ["Mittente noto non rende vero ogni allegato; wrapper PEC e alias vanno conservati come provenienza."],
        ["Regola attiva classifica solo il perimetro previsto e il test mostra esattamente i messaggi coinvolti."],
    ),
    54: page(
        ["health servizi/provider", "job/run", "errori", "configurazione non sensibile", "audit"],
        ["comandi amministrativi protetti", "retry/cancel controllato", "note operative"],
        [
            "Mostrare stato per servizio con timestamp, versione/commit, dipendenze e ultimo errore strutturato.",
            "Ogni contatore apre lista di job/errori; retry è selettivo e idempotente.",
            "Azioni distruttive o migrazioni mostrano dry-run, target esatti, conferma forte e rollback.",
        ],
        ["Refresh health e alert su errori persistenti, senza tempeste di notifiche."],
        ["Servizio/job ↔ run ↔ record coinvolti ↔ log/audit e pagina operativa."],
        ["Nessun segreto, stack trace sensibile o pulsante inutilizzabile; admin non significa autorizzazione automatica al pagamento."],
        ["Ogni stato è datato e verificabile; retry non duplica record e un errore apre il dettaglio utile."],
    ),
    55: page(
        ["utente amministratore", "stato enrollment MFA", "recovery policy", "audit"],
        ["enrollment/revoca MFA nel provider", "recovery code hash", "audit step-up"],
        [
            "Richiedere step-up prima di enrollment, rigenerazione recovery o revoca.",
            "Mostrare QR/secret soltanto nella fase di enrollment e confermare con codice valido.",
            "Recovery code mostrati una volta, conservati solo come hash e invalidati dopo uso/rigenerazione.",
        ],
        ["Revoca sessioni esistenti dopo operazioni sensibili e notifica all'amministratore."],
        ["Enrollment ↔ utente ↔ sessioni revocate ↔ audit sicurezza."],
        ["Secret MFA mai nei log/fogli/ZIP; nessuna disattivazione senza step-up e motivo."],
        ["Codice errato non attiva MFA; dopo attivazione il login richiede secondo fattore e revoca è auditata."],
    ),
    56: page(
        ["definizioni job", "import run", "record/errori per elemento", "checkpoint"],
        ["run batch, progresso, risultato per record e retry selettivo"],
        [
            "Creare un run con tipo, parametri validati, idempotency key, totale e checkpoint.",
            "Mostrare progresso reale, nuovi/aggiornati/duplicati/da verificare/errori e lista dei record.",
            "Retry elabora solo errori selezionati e conserva i successi; cancel interrompe in modo consistente.",
        ],
        ["Lock per job/sorgente, heartbeat, ripresa da checkpoint e backoff."],
        ["Run ↔ record origine/destinazione ↔ errori ↔ audit e pagina dominio."],
        ["Nessun batch senza dettaglio; retry totale non duplica successi; errori di un file non cancellano altri risultati."],
        ["Secondo run identico non crea nuovi record; progresso e conteggi finali coincidono con il dettaglio."],
    ),
    57: page(
        ["route legacy e mappa di redirect", "permessi utente"],
        ["Nessuna scrittura; solo audit del redirect se necessario."],
        [
            "Risolvere la route legacy verso /admin/batch-reprocessing mantenendo parametri sicuri supportati.",
            "Mostrare un avviso di percorso aggiornato solo se utile, poi usare lo stesso componente e gli stessi endpoint canonici.",
        ],
        ["Telemetry del traffico legacy per decidere la rimozione futura."],
        ["Route legacy → pagina elaborazioni canonica, senza duplicare stato o logica."],
        ["Nessun componente, router o writer duplicato; parametri sconosciuti vengono scartati."],
        ["Stesso contenuto e autorizzazioni della pagina canonica; nessuna chiamata a endpoint legacy paralleli."],
    ),
    58: page(
        ["utenti", "ruoli/permessi", "stato sessioni", "audit sicurezza"],
        ["profilo, ruolo, attivazione/disattivazione", "invito/reset tramite provider"],
        [
            "Elencare utenti con ruolo, stato, ultimo accesso e MFA senza esporre credenziali.",
            "Creazione invia un invito sicuro; modifica ruolo mostra differenze permessi e richiede step-up per privilegi elevati.",
            "Disattivazione revoca sessioni; eliminazione logica conserva audit e riferimenti storici.",
        ],
        ["Notifica sicurezza su cambio ruolo/reset e scadenza degli inviti."],
        ["Utente ↔ ruolo/permessi ↔ sessioni ↔ azioni audit."],
        ["Nessuna auto-elevazione; password/PIN mai leggibili; non cancellare l'ultimo amministratore attivo."],
        ["Ruolo applicato da API e UI; utente disattivato non accede e storico resta attribuito."],
    ),
    59: page(
        ["page_catalog", "router frontend/backend", "health e stato audit"],
        ["Nessuna scrittura applicativa; artefatto generato e fingerprint."],
        [
            "Generare albero per modulo dalle route canoniche con accesso, componente e stato verifica.",
            "Ogni nodo apre la pagina e mostra dipendenze/endpoint principali; alias legacy sono marcati.",
            "Separare raggiungibile, testato staticamente e verificato end-to-end.",
        ],
        ["Rigenerazione in CI e fallimento se catalogo/router/documentazione divergono."],
        ["Nodo pagina ↔ scheda logica ↔ componente ↔ endpoint ↔ test/health."],
        ["HTTP 200 non equivale a funzionamento; nessuna pagina scoperta fuori catalogo."],
        ["Catalogo contiene esattamente le route canoniche e ogni link risolve con il ruolo previsto."],
    ),
    60: page(
        ["fatture con classificazione IVA", "corrispettivi", "liquidazioni IVA", "F24", "crediti precedenti"],
        ["classificazione detraibilità", "versione liquidazione", "conferma/rettifica"],
        [
            "Calcolare IVA vendite da corrispettivi attivi deduplicati e IVA acquisti solo da classificazione esplicita iva_detraibile.",
            "Mostrare fatture incluse/escluse, aliquote, credito precedente, debito/credito periodo e formula.",
            "Una liquidazione confermata è versionata e non sovrascritta; trasmissione/pagamento F24 restano prove separate.",
        ],
        ["Ricalcolo bozza quando cambiano fonti aperte; blocco silenzioso su periodi confermati/trasmessi."],
        ["Liquidazione ↔ fatture/corrispettivi ↔ riga F24 ↔ PDF/quietanza/banca."],
        ["IVA esposta non è automaticamente detraibile; F24 e quietanza non sono movimento banca; nessun valore stimato come reale."],
        ["Totali riconciliabili alle righe incluse e una rettifica crea nuova versione con differenze esplicite."],
    ),
    61: page(
        ["fatture estere", "anagrafiche paese/valuta", "documenti integrazione/autofattura", "classificazione IVA"],
        ["stato verifica", "trattamento IVA motivato", "relazioni integrazione/autofattura"],
        [
            "Identificare paese, tipo fornitore, valuta, data cambio e natura dell'operazione dalla fattura.",
            "Proporre trattamento UE/extra-UE e necessità di integrazione/autofattura con regola fiscale/versione.",
            "Mostrare originale, documento integrativo e impatto IVA; conferma manuale quando dati fiscali non sono univoci.",
        ],
        ["Coda automatica per nuove fatture estere e controllo documenti integrativi mancanti."],
        ["Fattura estera ↔ fornitore ↔ originale ↔ integrazione/autofattura ↔ IVA/F24."],
        ["Non inventare cambio o trattamento; valuta/importo originale e controvalore restano distinti."],
        ["Ogni fattura ha stato motivato e documenti collegati; totali IVA usano solo classificazioni confermate."],
    ),
    62: page(
        ["bilancio/giornale", "fatture/corrispettivi", "personale/cespiti", "mappatura campi ISA"],
        ["snapshot ISA derivato, mapping/versione e note; nessuna modifica alle fonti"],
        [
            "Mappare ogni campo ISA a formula e conti/registri origine per esercizio.",
            "Calcolare valori solo da dati confermati e mostrare mancanti, esclusioni e quadrature.",
            "Esportare snapshot versionato con fingerprint delle fonti e drill-down per campo.",
        ],
        ["Ricalcolo bozza dopo variazioni; snapshot consegnato resta immutabile."],
        ["Campo ISA ↔ formula ↔ conti/righe/documenti origine ↔ snapshot/export."],
        ["Nessun valore inventato o zero al posto di fonte mancante; niente invio automatico."],
        ["Ogni valore è tracciabile e la somma delle righe origine coincide; mancanti restano espliciti."],
    ),
    63: page(
        ["Google Drive canonico", "metadati/hash/permessi", "indice Documenti", "watermark scansione"],
        ["indice Drive e stato indicizzazione; mai contenuto originale"],
        [
            "Scansionare cartelle autorizzate con paginazione e conservare Drive file ID, percorso, MIME, dimensione, checksum e permessi.",
            "Mostrare cartelle/documenti con filtri e stato indicizzato/non leggibile/duplicato esatto/da elaborare.",
            "Aprire l'originale e il record applicativo; una nuova scansione aggiorna metadati senza creare copie.",
        ],
        ["Scan incrementale con watermark, retry e rilevamento spostamenti tramite file ID."],
        ["File Drive ↔ indice Documenti ↔ import run ↔ record di dominio."],
        ["Errore permessi è esplicito; nessuna pulizia automatica; MD5/SHA esatto è requisito minimo per copia certa."],
        ["Conteggi verificabili per cartella, file apribili e seconda scansione senza nuovi record se Drive non cambia."],
    ),
    64: page(
        ["documenti atti", "enti/protocolli", "scadenze", "notifiche e relazioni"],
        ["atto canonico, metadati verificati, scadenze e stato pratica"],
        [
            "Importare originale e ricavare ente, tipo, protocollo, date, soggetto e scadenze con fonte per campo.",
            "Mostrare fascicolo con documento, eventi, note, responsabile e azioni richieste.",
            "Le scadenze generano attività/promemoria; stato completato richiede prova o nota coerente.",
        ],
        ["Classificazione e promemoria automatici solo su dati certi; OCR incerto resta in revisione."],
        ["Atto ↔ originale Drive ↔ ente/soggetto ↔ scadenze ↔ attività/notifiche."],
        ["Nessuna risposta/invio esterno automatico; non cancellare l'originale dopo elaborazione."],
        ["Ogni atto ha originale, protocollo e stato; alert apre l'atto e scompare solo a condizione risolta."],
    ),
    65: page(
        ["F24/righe tributo", "dichiarazioni", "quietanze", "movimenti banca", "scadenze/anomalie", "indice Drive"],
        ["Nessuna scrittura fiscale primaria; note/stato verifica e relazioni tramite servizi di dominio"],
        [
            "Costruire quadro per anno/tributo da fonti distinte, indicando presenza e stato di F24, dichiarazione, quietanza e banca.",
            "Mostrare totali solo quando semanticamente sommabili e permettere drill-down fino a riga tributo e PDF.",
            "Evidenziare documenti mancanti, crediti, differenze e relazioni ambigue con liste navigabili.",
            "Dichiarare la freschezza Drive e non nascondere una fonte indisponibile dietro uno zero.",
        ],
        ["Aggiornamento derivato dopo indicizzazione/import/riconciliazione e notifiche su anomalie persistenti."],
        ["Tributo ↔ F24/PDF ↔ dichiarazione ↔ quietanza ↔ banca ↔ scadenza e documento Drive."],
        ["F24, dichiarazione, quietanza e pagamento bancario non sono intercambiabili; nessuna associazione per importo solo."],
        ["Ricerca per anno/codice raggiunge tutte le prove; ogni anomalia ha lista e tutte le somme quadrano alle righe origine."],
    ),
}


REQUIRED_FIELDS = {"sources", "writes", "flow", "automations", "links", "guards", "acceptance"}


def validate_page_logic() -> None:
    if set(PAGE_LOGIC) != set(range(1, 66)):
        missing = sorted(set(range(1, 66)) - set(PAGE_LOGIC))
        extra = sorted(set(PAGE_LOGIC) - set(range(1, 66)))
        raise RuntimeError(f"Logica pagine incompleta: mancanti={missing}, extra={extra}")
    for page_id, value in PAGE_LOGIC.items():
        if set(value) != REQUIRED_FIELDS:
            raise RuntimeError(f"Campi logica pagina {page_id} non validi: {sorted(value)}")
        for field, rows in value.items():
            if not isinstance(rows, list) or not rows or any(not isinstance(row, str) or not row.strip() for row in rows):
                raise RuntimeError(f"Campo {field} della pagina {page_id} vuoto o non valido")


validate_page_logic()
