-- Gli id di menu_categories, menu_subcategories e menu_products li assegna il database (CLAUDE.md §5).
-- Prima li calcolavano le app con max(id)+1: il ponte Lotti con base 1.000.000 e ritentativo sulla
-- collisione, l'admin del Menu senza; due scritture vicine potevano prendere lo stesso numero.
--
-- Identity BY DEFAULT: un insert senza id riceve il prossimo numero della sequenza; gli insert con id
-- esplicito (seed, ripristino backup, 20261005210000_prodotto_unico) continuano a funzionare.
-- La sequenza parte oltre il massimo presente nella tabella, cosi' non collide con le righe esistenti.
-- Idempotente: l'identity si aggiunge solo se manca, il setval riallinea sempre al massimo reale.
--
-- Le viste public.menu_* sono `select *` senza colonne nuove: non vanno rifatte. L'identity non richiede
-- privilegi separati sulla sequenza per chi inserisce (la usa il default della colonna, non nextval()).
do $$
declare t text;
begin
  foreach t in array array['menu_categories', 'menu_subcategories', 'menu_products'] loop
    if not exists (
      select 1 from information_schema.columns
      where table_schema = 'menu' and table_name = t and column_name = 'id' and is_identity = 'YES'
    ) then
      execute format('alter table menu.%I alter column id add generated by default as identity', t);
    end if;
    execute format(
      'select setval(pg_get_serial_sequence(%L, ''id''), (select coalesce(max(id), 0) + 1 from menu.%I), false)',
      'menu.' || t, t
    );
  end loop;
end $$;
